ble_gatt_client: src/hci.c File Reference
hci.c File Reference
hci functions
#include <stdio.h>
#include <errno.h>
#include <fcntl.h>
#include <unistd.h>
#include <stdlib.h>
#include <string.h>
#include <poll.h>
#include <sys/param.h>
#include <sys/uio.h>
#include <sys/types.h>
#include <sys/ioctl.h>
#include <sys/socket.h>
#include "bluetooth.h"
#include "hci.h"
#include "hci_lib.h"
Data Structures
struct hci_map
Macros
#define MIN(x, y) ((x) < (y) ? (x) : (y))
Functions
static char * hci_bit2str (hci_map *m, unsigned int val)
static int hci_str2bit (hci_map *map, char *str, unsigned int *val)
static char * hci_uint2str (hci_map *m, unsigned int val)
static int hci_str2uint (hci_map *map, char *str, unsigned int *val)
char * hci_bustostr (int bus)
char * hci_dtypetostr (int type)
char * hci_typetostr (int type)
char * hci_dflagstostr (uint32_t flags)
char * hci_ptypetostr (unsigned int ptype)
int hci_strtoptype (char *str, unsigned int *val)
char * hci_scoptypetostr (unsigned int ptype)
int hci_strtoscoptype (char *str, unsigned int *val)
char * hci_lptostr (unsigned int lp)
int hci_strtolp (char *str, unsigned int *val)
char * hci_lmtostr (unsigned int lm)
int hci_strtolm (char *str, unsigned int *val)
char * hci_cmdtostr (unsigned int cmd)
char * hci_commandstostr (uint8_t *commands, char *pref, int width)
char * hci_vertostr (unsigned int ver)
int hci_strtover (char *str, unsigned int *ver)
char * lmp_vertostr (unsigned int ver)
int lmp_strtover (char *str, unsigned int *ver)
char * pal_vertostr (unsigned int ver)
int pal_strtover (char *str, unsigned int *ver)
char * lmp_featurestostr (uint8_t *features, char *pref, int width)
int hci_for_each_dev (int flag, int(*func)(int dd, int dev_id, long arg), long arg)
static int __other_bdaddr (int dd, int dev_id, long arg)
static int __same_bdaddr (int dd, int dev_id, long arg)
int hci_get_route (bdaddr_t *bdaddr)
int hci_devid (const char *str)
int hci_devinfo (int dev_id, struct hci_dev_info *di)
int hci_devba (int dev_id, bdaddr_t *bdaddr)
int hci_inquiry (int dev_id, int len, int nrsp, const uint8_t *lap, inquiry_info **ii, long flags)
int hci_open_dev (int dev_id)
int hci_close_dev (int dd)
int hci_send_cmd (int dd, uint16_t ogf, uint16_t ocf, uint8_t plen, void *param)
int hci_send_req (int dd, struct hci_request *r, int to)
int hci_create_connection (int dd, const bdaddr_t *bdaddr, uint16_t ptype, uint16_t clkoffset, uint8_t rswitch, uint16_t *handle, int to)
int hci_disconnect (int dd, uint16_t handle, uint8_t reason, int to)
int hci_le_add_white_list (int dd, const bdaddr_t *bdaddr, uint8_t type, int to)
int hci_le_rm_white_list (int dd, const bdaddr_t *bdaddr, uint8_t type, int to)
int hci_le_read_white_list_size (int dd, uint8_t *size, int to)
int hci_le_clear_white_list (int dd, int to)
int hci_le_add_resolving_list (int dd, const bdaddr_t *bdaddr, uint8_t type, uint8_t *peer_irk, uint8_t *local_irk, int to)
int hci_le_rm_resolving_list (int dd, const bdaddr_t *bdaddr, uint8_t type, int to)
int hci_le_clear_resolving_list (int dd, int to)
int hci_le_read_resolving_list_size (int dd, uint8_t *size, int to)
int hci_le_set_address_resolution_enable (int dd, uint8_t enable, int to)
int hci_read_local_name (int dd, int len, char *name, int to)
int hci_write_local_name (int dd, const char *name, int to)
int hci_read_remote_name_with_clock_offset (int dd, const bdaddr_t *bdaddr, uint8_t pscan_rep_mode, uint16_t clkoffset, int len, char *name, int to)
int hci_read_remote_name (int dd, const bdaddr_t *bdaddr, int len, char *name, int to)
int hci_read_remote_name_cancel (int dd, const bdaddr_t *bdaddr, int to)
int hci_read_remote_version (int dd, uint16_t handle, struct hci_version *ver, int to)
int hci_read_remote_features (int dd, uint16_t handle, uint8_t *features, int to)
int hci_read_remote_ext_features (int dd, uint16_t handle, uint8_t page, uint8_t *max_page, uint8_t *features, int to)
int hci_read_clock_offset (int dd, uint16_t handle, uint16_t *clkoffset, int to)
int hci_read_local_version (int dd, struct hci_version *ver, int to)
int hci_read_local_commands (int dd, uint8_t *commands, int to)
int hci_read_local_features (int dd, uint8_t *features, int to)
int hci_read_local_ext_features (int dd, uint8_t page, uint8_t *max_page, uint8_t *features, int to)
int hci_read_bd_addr (int dd, bdaddr_t *bdaddr, int to)
int hci_read_class_of_dev (int dd, uint8_t *cls, int to)
int hci_write_class_of_dev (int dd, uint32_t cls, int to)
int hci_read_voice_setting (int dd, uint16_t *vs, int to)
int hci_write_voice_setting (int dd, uint16_t vs, int to)
int hci_read_current_iac_lap (int dd, uint8_t *num_iac, uint8_t *lap, int to)
int hci_write_current_iac_lap (int dd, uint8_t num_iac, uint8_t *lap, int to)
int hci_read_stored_link_key (int dd, bdaddr_t *bdaddr, uint8_t all, int to)
int hci_write_stored_link_key (int dd, bdaddr_t *bdaddr, uint8_t *key, int to)
int hci_delete_stored_link_key (int dd, bdaddr_t *bdaddr, uint8_t all, int to)
int hci_authenticate_link (int dd, uint16_t handle, int to)
int hci_encrypt_link (int dd, uint16_t handle, uint8_t encrypt, int to)
int hci_change_link_key (int dd, uint16_t handle, int to)
int hci_switch_role (int dd, bdaddr_t *bdaddr, uint8_t role, int to)
int hci_park_mode (int dd, uint16_t handle, uint16_t max_interval, uint16_t min_interval, int to)
int hci_exit_park_mode (int dd, uint16_t handle, int to)
int hci_read_inquiry_scan_type (int dd, uint8_t *type, int to)
int hci_write_inquiry_scan_type (int dd, uint8_t type, int to)
int hci_read_inquiry_mode (int dd, uint8_t *mode, int to)
int hci_write_inquiry_mode (int dd, uint8_t mode, int to)
int hci_read_afh_mode (int dd, uint8_t *mode, int to)
int hci_write_afh_mode (int dd, uint8_t mode, int to)
int hci_read_ext_inquiry_response (int dd, uint8_t *fec, uint8_t *data, int to)
int hci_write_ext_inquiry_response (int dd, uint8_t fec, uint8_t *data, int to)
int hci_read_simple_pairing_mode (int dd, uint8_t *mode, int to)
int hci_write_simple_pairing_mode (int dd, uint8_t mode, int to)
int hci_read_local_oob_data (int dd, uint8_t *hash, uint8_t *randomizer, int to)
int hci_read_inq_response_tx_power_level (int dd, int8_t *level, int to)
int hci_read_inquiry_transmit_power_level (int dd, int8_t *level, int to)
int hci_write_inquiry_transmit_power_level (int dd, int8_t level, int to)
int hci_read_transmit_power_level (int dd, uint16_t handle, uint8_t type, int8_t *level, int to)
int hci_read_link_policy (int dd, uint16_t handle, uint16_t *policy, int to)
int hci_write_link_policy (int dd, uint16_t handle, uint16_t policy, int to)
int hci_read_link_supervision_timeout (int dd, uint16_t handle, uint16_t *timeout, int to)
int hci_write_link_supervision_timeout (int dd, uint16_t handle, uint16_t timeout, int to)
int hci_set_afh_classification (int dd, uint8_t *map, int to)
int hci_read_link_quality (int dd, uint16_t handle, uint8_t *link_quality, int to)
int hci_read_rssi (int dd, uint16_t handle, int8_t *rssi, int to)
int hci_read_afh_map (int dd, uint16_t handle, uint8_t *mode, uint8_t *map, int to)
int hci_read_clock (int dd, uint16_t handle, uint8_t which, uint32_t *clock, uint16_t *accuracy, int to)
int hci_le_set_scan_enable (int dd, uint8_t enable, uint8_t filter_dup, int to)
int hci_le_set_scan_parameters (int dd, uint8_t type, uint16_t interval, uint16_t window, uint8_t own_type, uint8_t filter, int to)
int hci_le_set_advertise_enable (int dd, uint8_t enable, int to)
int hci_le_create_conn (int dd, uint16_t interval, uint16_t window, uint8_t initiator_filter, uint8_t peer_bdaddr_type, bdaddr_t peer_bdaddr, uint8_t own_bdaddr_type, uint16_t min_interval, uint16_t max_interval, uint16_t latency, uint16_t supervision_timeout, uint16_t min_ce_length, uint16_t max_ce_length, uint16_t *handle, int to)
int hci_le_conn_update (int dd, uint16_t handle, uint16_t min_interval, uint16_t max_interval, uint16_t latency, uint16_t supervision_timeout, int to)
int hci_le_read_remote_features (int dd, uint16_t handle, uint8_t *features, int to)
Variables
static hci_map dev_flags_map []
static hci_map pkt_type_map []
static hci_map sco_ptype_map []
static hci_map link_policy_map []
static hci_map link_mode_map []
static hci_map commands_map []
static hci_map ver_map []
static hci_map pal_map []
static hci_map lmp_features_map [8][9]
Detailed Description
hci functions
Author
Gilbert Brault
Copyright
Gilbert Brault 2015 the original work comes from bluez v5.39 value add: documenting main features
Definition in file hci.c.
Macro Definition Documentation
#define MIN (x, y) ((x) < (y) ? (x) : (y))
Definition at line 59 of file hci.c.
Referenced by hci_send_req().
Function Documentation
static int __other_bdaddr (int dd, int dev_id, long arg) static
Parameters
dd
dev_id
arg
Returns
Definition at line 1075 of file hci.c.
References bacmp(), hci_dev_info::bdaddr, hci_dev_info::dev_id, hci_dev_info::flags, HCI_RAW, hci_test_bit(), and HCIGETDEVINFO.
Referenced by hci_get_route().
static int __same_bdaddr (int dd, int dev_id, long arg) static
Parameters
dd
dev_id
arg
Returns
Definition at line 1095 of file hci.c.
References bacmp(), hci_dev_info::bdaddr, hci_dev_info::dev_id, and HCIGETDEVINFO.
Referenced by hci_devid(), and hci_get_route().
int hci_authenticate_link (int dd, uint16_t handle, int to)
Parameters
dd
handle
to
Returns
Definition at line 2696 of file hci.c.
References AUTH_REQUESTED_CP_SIZE, hci_request::clen, hci_request::cparam, hci_request::event, EVT_AUTH_COMPLETE, EVT_AUTH_COMPLETE_SIZE, hci_send_req(), hci_request::ocf, OCF_AUTH_REQUESTED, hci_request::ogf, OGF_LINK_CTL, hci_request::rlen, and hci_request::rparam.
static char* hci_bit2str (hci_map * m, unsigned int val) static
lookup the numeric code val into the hci_map m and return the matching string
Parameters
m pointer to the hci_map
val code to match
Returns
string matching the code (val) from the hci_map
Definition at line 74 of file hci.c.
References hci_map::str, and hci_map::val.
Referenced by hci_lmtostr(), hci_lptostr(), hci_ptypetostr(), and hci_scoptypetostr().
char* hci_bustostr (int bus)
return a string corresponding to the bus code (see HCI bus types in hci.h)
Parameters
bus bus code
Returns
string corresponding to the bus code (NULL if error)
Definition at line 189 of file hci.c.
References HCI_PCCARD, HCI_PCI, HCI_RS232, HCI_SDIO, HCI_UART, HCI_USB, and HCI_VIRTUAL.
Referenced by hci_dtypetostr().
int hci_change_link_key (int dd, uint16_t handle, int to)
Parameters
dd
handle
to
Returns
Definition at line 2768 of file hci.c.
References CHANGE_CONN_LINK_KEY_CP_SIZE, hci_request::clen, hci_request::cparam, hci_request::event, EVT_CHANGE_CONN_LINK_KEY_COMPLETE, EVT_CHANGE_CONN_LINK_KEY_COMPLETE_SIZE, hci_send_req(), hci_request::ocf, OCF_CHANGE_CONN_LINK_KEY, hci_request::ogf, OGF_LINK_CTL, hci_request::rlen, and hci_request::rparam.
int hci_close_dev (int dd)
Close the device
Parameters
dd Device descriptor returned by hci_open_dev.
Returns
0 if OK or -1 if failure
Definition at line 1326 of file hci.c.
char* hci_cmdtostr (unsigned int cmd)
translate a command code into an english sentence
use the commands_map table which is an array of structures { "english sentence", command code }
Parameters
cmd command code value
Returns
english sentence corresponding to the command code (NULL if error)
Definition at line 722 of file hci.c.
References hci_uint2str().
char* hci_commandstostr (uint8_t * commands, char * pref, int width)
translate a byte array of bit "commands" into a series of corresponding english strings which is returned
Parameters
commands an array of bytes corresponding to a list of encoded commands
pref prefix to add to str (if pref !=NULL pref will be the first concatenated string)
width
Returns
NULL if error else str which is a string of concatenated commands separated by /0
Definition at line 735 of file hci.c.
References bt_malloc(), commands_map, hci_map::str, and hci_map::val.
int hci_create_connection (int dd, const bdaddr_t * bdaddr, uint16_t ptype, uint16_t clkoffset, uint8_t rswitch, uint16_t * handle, int to)
Parameters
dd
bdaddr
ptype
clkoffset
rswitch
handle
to
Returns
Definition at line 1539 of file hci.c.
References bacpy(), hci_request::clen, hci_request::cparam, CREATE_CONN_CP_SIZE, hci_request::event, EVT_CONN_COMPLETE, EVT_CONN_COMPLETE_SIZE, hci_send_req(), hci_request::ocf, OCF_CREATE_CONN, hci_request::ogf, OGF_LINK_CTL, hci_request::rlen, and hci_request::rparam.
int hci_delete_stored_link_key (int dd, bdaddr_t * bdaddr, uint8_t all, int to)
Parameters
dd
bdaddr
all
to
Returns
Definition at line 2670 of file hci.c.
References bacpy(), hci_request::clen, hci_request::cparam, DELETE_STORED_LINK_KEY_CP_SIZE, hci_send_req(), hci_request::ocf, OCF_DELETE_STORED_LINK_KEY, hci_request::ogf, and OGF_HOST_CTL.
int hci_devba (int dev_id, bdaddr_t * bdaddr)
Parameters
dev_id
bdaddr
Returns
0 = OK, -1 = Error
Definition at line 1182 of file hci.c.
References bacpy(), hci_dev_info::bdaddr, hci_dev_info::flags, hci_devinfo(), hci_test_bit(), and HCI_UP.
Referenced by hci_devid(), and main().
int hci_devid (const char * str)
return the bt device number
Parameters
str string should be hci<n>
Returns
bt device number (-1 if error)
Definition at line 1130 of file hci.c.
References __same_bdaddr(), hci_devba(), hci_for_each_dev(), HCI_UP, and str2ba().
Referenced by main().
int hci_devinfo (int dev_id, struct hci_dev_info * di)
get device info given device id
Parameters
dev_id device id
di device info structure if ok
Returns
0 info structure set else error
Definition at line 1155 of file hci.c.
References AF_BLUETOOTH, BTPROTO_HCI, hci_dev_info::dev_id, and HCIGETDEVINFO.
Referenced by hci_devba().
char* hci_dflagstostr (uint32_t flags)
return the HCI device flags string given its code
Parameters
flags HCI device flags code
Returns
HCI device flags string (NULL if error)
Definition at line 260 of file hci.c.
References bt_malloc(), dev_flags_map, hci_test_bit(), HCI_UP, hci_map::str, and hci_map::val.
int hci_disconnect (int dd, uint16_t handle, uint8_t reason, int to)
Parameters
dd
handle
reason
to
Returns
Definition at line 1584 of file hci.c.
References hci_request::clen, hci_request::cparam, DISCONNECT_CP_SIZE, hci_request::event, EVT_DISCONN_COMPLETE, EVT_DISCONN_COMPLETE_SIZE, hci_send_req(), hci_request::ocf, OCF_DISCONNECT, hci_request::ogf, OGF_LINK_CTL, hci_request::rlen, and hci_request::rparam.
char* hci_dtypetostr (int type)
return the bus string according to the bus code (type)
Parameters
type bus code
Returns
bus string (NULL if error)
Definition at line 217 of file hci.c.
References hci_bustostr().
int hci_encrypt_link (int dd, uint16_t handle, uint8_t encrypt, int to)
Parameters
dd
handle
encrypt
to
Returns
Definition at line 2732 of file hci.c.
References hci_request::clen, hci_request::cparam, hci_request::event, EVT_ENCRYPT_CHANGE, EVT_ENCRYPT_CHANGE_SIZE, hci_send_req(), hci_request::ocf, OCF_SET_CONN_ENCRYPT, hci_request::ogf, OGF_LINK_CTL, hci_request::rlen, hci_request::rparam, and SET_CONN_ENCRYPT_CP_SIZE.
int hci_exit_park_mode (int dd, uint16_t handle, int to)
Parameters
dd
handle
to
Returns
Definition at line 2881 of file hci.c.
References hci_request::clen, hci_request::cparam, hci_request::event, EVT_MODE_CHANGE, EVT_MODE_CHANGE_SIZE, EXIT_PARK_MODE_CP_SIZE, hci_send_req(), hci_request::ocf, OCF_EXIT_PARK_MODE, hci_request::ogf, OGF_LINK_POLICY, hci_request::rlen, and hci_request::rparam.
int hci_for_each_dev (int flag, int(*)(int dd, int dev_id, long arg) func, long arg)
return the bt device number
Parameters
flag
func
arg
Returns
Definition at line 1019 of file hci.c.
References AF_BLUETOOTH, BTPROTO_HCI, hci_dev_req::dev_id, hci_dev_list_req::dev_num, hci_dev_req::dev_opt, hci_dev_list_req::dev_req, func, HCI_MAX_DEV, hci_test_bit(), and HCIGETDEVLIST.
Referenced by hci_devid(), and hci_get_route().
int hci_get_route (bdaddr_t * bdaddr)
Parameters
bdaddr
Returns
Definition at line 1111 of file hci.c.
References __other_bdaddr(), __same_bdaddr(), BDADDR_ANY, hci_dev_info::dev_id, hci_for_each_dev(), and HCI_UP.
Referenced by hci_inquiry().
int hci_inquiry (int dev_id, int len, int nrsp, const uint8_t * lap, inquiry_info ** ii, long flags)
Parameters
dev_id
len
nrsp
lap
ii
flags
Returns
Definition at line 1212 of file hci.c.
References AF_BLUETOOTH, BTPROTO_HCI, hci_inquiry_req::dev_id, hci_inquiry_req::flags, hci_get_route(), HCIINQUIRY, hci_inquiry_req::lap, hci_inquiry_req::length, and hci_inquiry_req::num_rsp.
int hci_le_add_resolving_list (int dd, const bdaddr_t * bdaddr, uint8_t type, uint8_t * peer_irk, uint8_t * local_irk, int to)
Parameters
dd
bdaddr
type
peer_irk
local_irk
to
Returns
Definition at line 1764 of file hci.c.
References bacpy(), hci_request::clen, hci_request::cparam, hci_send_req(), LE_ADD_DEVICE_TO_RESOLV_LIST_CP_SIZE, hci_request::ocf, OCF_LE_ADD_DEVICE_TO_RESOLV_LIST, hci_request::ogf, OGF_LE_CTL, hci_request::rlen, hci_request::rparam, and type.
int hci_le_add_white_list (int dd, const bdaddr_t * bdaddr, uint8_t type, int to)
Parameters
dd
bdaddr
type
to
Returns
Definition at line 1622 of file hci.c.
References bacpy(), hci_request::clen, hci_request::cparam, hci_send_req(), LE_ADD_DEVICE_TO_WHITE_LIST_CP_SIZE, hci_request::ocf, OCF_LE_ADD_DEVICE_TO_WHITE_LIST, hci_request::ogf, OGF_LE_CTL, hci_request::rlen, hci_request::rparam, and type.
int hci_le_clear_resolving_list (int dd, int to)
Parameters
dd
to
Returns
Definition at line 1843 of file hci.c.
References hci_send_req(), hci_request::ocf, OCF_LE_CLEAR_RESOLV_LIST, hci_request::ogf, OGF_LE_CTL, hci_request::rlen, and hci_request::rparam.
int hci_le_clear_white_list (int dd, int to)
Parameters
dd
to
Returns
Definition at line 1731 of file hci.c.
References hci_send_req(), hci_request::ocf, OCF_LE_CLEAR_WHITE_LIST, hci_request::ogf, OGF_LE_CTL, hci_request::rlen, and hci_request::rparam.
int hci_le_conn_update (int dd, uint16_t handle, uint16_t min_interval, uint16_t max_interval, uint16_t latency, uint16_t supervision_timeout, int to)
Parameters
dd
handle
min_interval
max_interval
latency
supervision_timeout
to
Returns
Definition at line 3936 of file hci.c.
References hci_request::clen, hci_request::cparam, hci_request::event, EVT_LE_CONN_UPDATE_COMPLETE, hci_send_req(), htobs, LE_CONN_UPDATE_CP_SIZE, hci_request::ocf, OCF_LE_CONN_UPDATE, hci_request::ogf, OGF_LE_CTL, hci_request::rlen, and hci_request::rparam.
int hci_le_create_conn (int dd, uint16_t interval, uint16_t window, uint8_t initiator_filter, uint8_t peer_bdaddr_type, bdaddr_t peer_bdaddr, uint8_t own_bdaddr_type, uint16_t min_interval, uint16_t max_interval, uint16_t latency, uint16_t supervision_timeout, uint16_t min_ce_length, uint16_t max_ce_length, uint16_t * handle, int to)
Parameters
dd
interval
window
initiator_filter
peer_bdaddr_type
peer_bdaddr
own_bdaddr_type
min_interval
max_interval
latency
supervision_timeout
min_ce_length
max_ce_length
handle
to
Returns
Definition at line 3875 of file hci.c.
References hci_request::clen, hci_request::cparam, hci_request::event, EVT_CONN_COMPLETE_SIZE, EVT_LE_CONN_COMPLETE, hci_send_req(), LE_CREATE_CONN_CP_SIZE, hci_request::ocf, OCF_LE_CREATE_CONN, hci_request::ogf, OGF_LE_CTL, hci_request::rlen, and hci_request::rparam.
int hci_le_read_remote_features (int dd, uint16_t handle, uint8_t * features, int to)
Parameters
dd
handle
features
to
Returns
Definition at line 3982 of file hci.c.
References hci_request::clen, hci_request::cparam, hci_request::event, EVT_LE_READ_REMOTE_USED_FEATURES_COMPLETE, EVT_LE_READ_REMOTE_USED_FEATURES_COMPLETE_SIZE, hci_send_req(), LE_READ_REMOTE_USED_FEATURES_CP_SIZE, hci_request::ocf, OCF_LE_READ_REMOTE_USED_FEATURES, hci_request::ogf, OGF_LE_CTL, hci_request::rlen, and hci_request::rparam.
int hci_le_read_resolving_list_size (int dd, uint8_t * size, int to)
Parameters
dd
size
to
Returns
Definition at line 1873 of file hci.c.
References hci_send_req(), LE_READ_RESOLV_LIST_SIZE_RP_SIZE, hci_request::ocf, OCF_LE_READ_RESOLV_LIST_SIZE, hci_request::ogf, OGF_LE_CTL, hci_request::rlen, and hci_request::rparam.
int hci_le_read_white_list_size (int dd, uint8_t * size, int to)
Parameters
dd
size
to
Returns
Definition at line 1697 of file hci.c.
References hci_send_req(), LE_READ_WHITE_LIST_SIZE_RP_SIZE, hci_request::ocf, OCF_LE_READ_WHITE_LIST_SIZE, hci_request::ogf, OGF_LE_CTL, hci_request::rlen, and hci_request::rparam.
int hci_le_rm_resolving_list (int dd, const bdaddr_t * bdaddr, uint8_t type, int to)
Parameters
dd
bdaddr
type
to
Returns
Definition at line 1807 of file hci.c.
References bacpy(), hci_request::clen, hci_request::cparam, hci_send_req(), LE_REMOVE_DEVICE_FROM_RESOLV_LIST_CP_SIZE, hci_request::ocf, OCF_LE_REMOVE_DEVICE_FROM_RESOLV_LIST, hci_request::ogf, OGF_LE_CTL, hci_request::rlen, hci_request::rparam, and type.
int hci_le_rm_white_list (int dd, const bdaddr_t * bdaddr, uint8_t type, int to)
Parameters
dd
bdaddr
type
to
Returns
Definition at line 1660 of file hci.c.
References bacpy(), hci_request::clen, hci_request::cparam, hci_send_req(), LE_REMOVE_DEVICE_FROM_WHITE_LIST_CP_SIZE, hci_request::ocf, OCF_LE_REMOVE_DEVICE_FROM_WHITE_LIST, hci_request::ogf, OGF_LE_CTL, hci_request::rlen, hci_request::rparam, and type.
int hci_le_set_address_resolution_enable (int dd, uint8_t enable, int to)
Parameters
dd
enable
to
Returns
Definition at line 1908 of file hci.c.
References hci_request::clen, hci_request::cparam, hci_send_req(), LE_SET_ADDRESS_RESOLUTION_ENABLE_CP_SIZE, hci_request::ocf, OCF_LE_SET_ADDRESS_RESOLUTION_ENABLE, hci_request::ogf, OGF_LE_CTL, hci_request::rlen, and hci_request::rparam.
int hci_le_set_advertise_enable (int dd, uint8_t enable, int to)
Parameters
dd
enable
to
Returns
Definition at line 3827 of file hci.c.
References hci_request::clen, hci_request::cparam, hci_send_req(), LE_SET_ADVERTISE_ENABLE_CP_SIZE, hci_request::ocf, OCF_LE_SET_ADVERTISE_ENABLE, hci_request::ogf, OGF_LE_CTL, hci_request::rlen, and hci_request::rparam.
int hci_le_set_scan_enable (int dd, uint8_t enable, uint8_t filter_dup, int to)
Parameters
dd
enable
filter_dup
to
Returns
Definition at line 3744 of file hci.c.
References hci_request::clen, hci_request::cparam, hci_send_req(), LE_SET_SCAN_ENABLE_CP_SIZE, hci_request::ocf, OCF_LE_SET_SCAN_ENABLE, hci_request::ogf, OGF_LE_CTL, hci_request::rlen, and hci_request::rparam.
int hci_le_set_scan_parameters (int dd, uint8_t type, uint16_t interval, uint16_t window, uint8_t own_type, uint8_t filter, int to)
Parameters
dd
type
interval
window
own_type
filter
to
Returns
Definition at line 3785 of file hci.c.
References hci_request::clen, hci_request::cparam, hci_send_req(), LE_SET_SCAN_PARAMETERS_CP_SIZE, hci_request::ocf, OCF_LE_SET_SCAN_PARAMETERS, hci_request::ogf, OGF_LE_CTL, hci_request::rlen, hci_request::rparam, and type.
char* hci_lmtostr (unsigned int lm)
return the Link mode mapping string given the code
Parameters
lm Link mode mapping code
Returns
Link mode mapping string (NULL if error)
Definition at line 415 of file hci.c.
References bt_free(), bt_malloc(), hci_bit2str(), and HCI_LM_MASTER.
char* hci_lptostr (unsigned int lp)
return the Link policy mapping string given the code
Parameters
lp Link policy mapping code
Returns
Link policy mapping string (NULL if error)
Definition at line 379 of file hci.c.
References hci_bit2str().
int hci_open_dev (int dev_id)
Open HCI device.
Parameters
dev_id integer device address
Returns
device descriptor (dd): a bluetooth socket
Definition at line 1287 of file hci.c.
References AF_BLUETOOTH, BTPROTO_HCI, sockaddr_hci::hci_dev, and sockaddr_hci::hci_family.
int hci_park_mode (int dd, uint16_t handle, uint16_t max_interval, uint16_t min_interval, int to)
Parameters
dd
handle
max_interval
min_interval
to
Returns
Definition at line 2841 of file hci.c.
References hci_request::clen, hci_request::cparam, hci_request::event, EVT_MODE_CHANGE, EVT_MODE_CHANGE_SIZE, hci_send_req(), hci_request::ocf, OCF_PARK_MODE, hci_request::ogf, OGF_LINK_POLICY, PARK_MODE_CP_SIZE, hci_request::rlen, and hci_request::rparam.
char* hci_ptypetostr (unsigned int ptype)
return the HCI packet type string given the code
Parameters
ptype HCI packet type
Returns
HCI packet type string (NULL if error)
Definition at line 323 of file hci.c.
References hci_bit2str().
int hci_read_afh_map (int dd, uint16_t handle, uint8_t * mode, uint8_t * map, int to)
Parameters
dd
handle
mode
map
to
Returns
Definition at line 3665 of file hci.c.
References hci_request::clen, hci_request::cparam, hci_send_req(), hci_request::ocf, OCF_READ_AFH_MAP, hci_request::ogf, OGF_STATUS_PARAM, READ_AFH_MAP_RP_SIZE, hci_request::rlen, and hci_request::rparam.
int hci_read_afh_mode (int dd, uint8_t * mode, int to)
Parameters
dd
mode
to
Returns
Definition at line 3052 of file hci.c.
References hci_send_req(), hci_request::ocf, OCF_READ_AFH_MODE, hci_request::ogf, OGF_HOST_CTL, READ_AFH_MODE_RP_SIZE, hci_request::rlen, and hci_request::rparam.
int hci_read_bd_addr (int dd, bdaddr_t * bdaddr, int to)
Parameters
dd
bdaddr
to
Returns
Definition at line 2412 of file hci.c.
References bacpy(), hci_send_req(), hci_request::ocf, OCF_READ_BD_ADDR, hci_request::ogf, OGF_INFO_PARAM, READ_BD_ADDR_RP_SIZE, hci_request::rlen, and hci_request::rparam.
int hci_read_class_of_dev (int dd, uint8_t * cls, int to)
Parameters
dd
cls
to
Returns
Definition at line 2445 of file hci.c.
References hci_send_req(), hci_request::ocf, OCF_READ_CLASS_OF_DEV, hci_request::ogf, OGF_HOST_CTL, READ_CLASS_OF_DEV_RP_SIZE, hci_request::rlen, and hci_request::rparam.
int hci_read_clock (int dd, uint16_t handle, uint8_t which, uint32_t * clock, uint16_t * accuracy, int to)
Parameters
dd
handle
which
clock
accuracy
to
Returns
Definition at line 3703 of file hci.c.
References hci_request::clen, hci_request::cparam, hci_send_req(), hci_request::ocf, OCF_READ_CLOCK, hci_request::ogf, OGF_STATUS_PARAM, READ_CLOCK_CP_SIZE, READ_CLOCK_RP_SIZE, hci_request::rlen, and hci_request::rparam.
int hci_read_clock_offset (int dd, uint16_t handle, uint16_t * clkoffset, int to)
Parameters
dd
handle
clkoffset
to
Returns
Definition at line 2229 of file hci.c.
References hci_request::clen, hci_request::cparam, hci_request::event, EVT_READ_CLOCK_OFFSET_COMPLETE, EVT_READ_CLOCK_OFFSET_COMPLETE_SIZE, hci_send_req(), hci_request::ocf, OCF_READ_CLOCK_OFFSET, hci_request::ogf, OGF_LINK_CTL, READ_CLOCK_OFFSET_CP_SIZE, hci_request::rlen, and hci_request::rparam.
int hci_read_current_iac_lap (int dd, uint8_t * num_iac, uint8_t * lap, int to)
Parameters
dd
num_iac
lap
to
Returns
Definition at line 2555 of file hci.c.
References hci_send_req(), hci_request::ocf, OCF_READ_CURRENT_IAC_LAP, hci_request::ogf, OGF_HOST_CTL, READ_CURRENT_IAC_LAP_RP_SIZE, hci_request::rlen, and hci_request::rparam.
int hci_read_ext_inquiry_response (int dd, uint8_t * fec, uint8_t * data, int to)
Parameters
dd
fec
data
to
Returns
Definition at line 3120 of file hci.c.
References HCI_MAX_EIR_LENGTH, hci_send_req(), hci_request::ocf, OCF_READ_EXT_INQUIRY_RESPONSE, hci_request::ogf, OGF_HOST_CTL, READ_EXT_INQUIRY_RESPONSE_RP_SIZE, hci_request::rlen, and hci_request::rparam.
int hci_read_inq_response_tx_power_level (int dd, int8_t * level, int to)
Parameters
dd
level
to
Returns
Definition at line 3291 of file hci.c.
References hci_send_req(), hci_request::ocf, OCF_READ_INQ_RESPONSE_TX_POWER_LEVEL, hci_request::ogf, OGF_HOST_CTL, READ_INQ_RESPONSE_TX_POWER_LEVEL_RP_SIZE, hci_request::rlen, and hci_request::rparam.
Referenced by hci_read_inquiry_transmit_power_level().
int hci_read_inquiry_mode (int dd, uint8_t * mode, int to)
Parameters
dd
mode
to
Returns
Definition at line 2985 of file hci.c.
References hci_send_req(), hci_request::ocf, OCF_READ_INQUIRY_MODE, hci_request::ogf, OGF_HOST_CTL, READ_INQUIRY_MODE_RP_SIZE, hci_request::rlen, and hci_request::rparam.
int hci_read_inquiry_scan_type (int dd, uint8_t * type, int to)
Parameters
dd
type
to
Returns
Definition at line 2918 of file hci.c.
References hci_send_req(), hci_request::ocf, OCF_READ_INQUIRY_SCAN_TYPE, hci_request::ogf, OGF_HOST_CTL, READ_INQUIRY_SCAN_TYPE_RP_SIZE, hci_request::rlen, and hci_request::rparam.
int hci_read_inquiry_transmit_power_level (int dd, int8_t * level, int to)
Parameters
dd
level
to
Returns
Definition at line 3322 of file hci.c.
References hci_read_inq_response_tx_power_level().
int hci_read_link_policy (int dd, uint16_t handle, uint16_t * policy, int to)
Parameters
dd
handle
policy
to
Returns
Definition at line 3413 of file hci.c.
References hci_request::clen, hci_request::cparam, hci_send_req(), hci_request::ocf, OCF_READ_LINK_POLICY, hci_request::ogf, OGF_LINK_POLICY, READ_LINK_POLICY_RP_SIZE, hci_request::rlen, and hci_request::rparam.
int hci_read_link_quality (int dd, uint16_t handle, uint8_t * link_quality, int to)
Parameters
dd
handle
link_quality
to
Returns
Definition at line 3595 of file hci.c.
References hci_request::clen, hci_request::cparam, hci_send_req(), hci_request::ocf, OCF_READ_LINK_QUALITY, hci_request::ogf, OGF_STATUS_PARAM, READ_LINK_QUALITY_RP_SIZE, hci_request::rlen, and hci_request::rparam.
int hci_read_link_supervision_timeout (int dd, uint16_t handle, uint16_t * timeout, int to)
Parameters
dd
handle
timeout
to
Returns
Definition at line 3485 of file hci.c.
References hci_request::clen, hci_request::cparam, hci_send_req(), hci_request::ocf, OCF_READ_LINK_SUPERVISION_TIMEOUT, hci_request::ogf, OGF_HOST_CTL, READ_LINK_SUPERVISION_TIMEOUT_RP_SIZE, hci_request::rlen, and hci_request::rparam.
int hci_read_local_commands (int dd, uint8_t * commands, int to)
Parameters
dd
commands
to
Returns
Definition at line 2302 of file hci.c.
References hci_send_req(), hci_request::ocf, OCF_READ_LOCAL_COMMANDS, hci_request::ogf, OGF_INFO_PARAM, READ_LOCAL_COMMANDS_RP_SIZE, hci_request::rlen, and hci_request::rparam.
int hci_read_local_ext_features (int dd, uint8_t page, uint8_t * max_page, uint8_t * features, int to)
Parameters
dd
page
max_page
features
to
Returns
Definition at line 2370 of file hci.c.
References hci_request::clen, hci_request::cparam, hci_send_req(), hci_request::ocf, OCF_READ_LOCAL_EXT_FEATURES, hci_request::ogf, OGF_INFO_PARAM, READ_LOCAL_EXT_FEATURES_CP_SIZE, READ_LOCAL_EXT_FEATURES_RP_SIZE, hci_request::rlen, and hci_request::rparam.
int hci_read_local_features (int dd, uint8_t * features, int to)
Parameters
dd
features
to
Returns
Definition at line 2335 of file hci.c.
References hci_send_req(), hci_request::ocf, OCF_READ_LOCAL_FEATURES, hci_request::ogf, OGF_INFO_PARAM, READ_LOCAL_FEATURES_RP_SIZE, hci_request::rlen, and hci_request::rparam.
int hci_read_local_name (int dd, int len, char * name, int to)
Parameters
dd
len
name
to
Returns
Definition at line 1943 of file hci.c.
References hci_send_req(), hci_request::ocf, OCF_READ_LOCAL_NAME, hci_request::ogf, OGF_HOST_CTL, READ_LOCAL_NAME_RP_SIZE, hci_request::rlen, and hci_request::rparam.
int hci_read_local_oob_data (int dd, uint8_t * hash, uint8_t * randomizer, int to)
Parameters
dd
hash
randomizer
to
Returns
Definition at line 3259 of file hci.c.
References hci_send_req(), hci_request::ocf, OCF_READ_LOCAL_OOB_DATA, hci_request::ogf, OGF_HOST_CTL, READ_LOCAL_OOB_DATA_RP_SIZE, hci_request::rlen, and hci_request::rparam.
int hci_read_local_version (int dd, struct hci_version * ver, int to)
Parameters
dd
ver
to
Returns
Definition at line 2267 of file hci.c.
References btohs, hci_version::hci_rev, hci_send_req(), hci_version::hci_ver, hci_version::lmp_subver, hci_version::lmp_ver, hci_version::manufacturer, hci_request::ocf, OCF_READ_LOCAL_VERSION, hci_request::ogf, OGF_INFO_PARAM, READ_LOCAL_VERSION_RP_SIZE, hci_request::rlen, and hci_request::rparam.
int hci_read_remote_ext_features (int dd, uint16_t handle, uint8_t page, uint8_t * max_page, uint8_t * features, int to)
Parameters
dd
handle
page
max_page
features
to
Returns
Definition at line 2182 of file hci.c.
References hci_request::clen, hci_request::cparam, hci_request::event, EVT_READ_REMOTE_EXT_FEATURES_COMPLETE, EVT_READ_REMOTE_EXT_FEATURES_COMPLETE_SIZE, hci_send_req(), hci_request::ocf, OCF_READ_REMOTE_EXT_FEATURES, hci_request::ogf, OGF_LINK_CTL, READ_REMOTE_EXT_FEATURES_CP_SIZE, hci_request::rlen, and hci_request::rparam.
int hci_read_remote_features (int dd, uint16_t handle, uint8_t * features, int to)
Parameters
dd
handle
features
to
Returns
Definition at line 2139 of file hci.c.
References hci_request::clen, hci_request::cparam, hci_request::event, EVT_READ_REMOTE_FEATURES_COMPLETE, EVT_READ_REMOTE_FEATURES_COMPLETE_SIZE, hci_send_req(), hci_request::ocf, OCF_READ_REMOTE_FEATURES, hci_request::ogf, OGF_LINK_CTL, READ_REMOTE_FEATURES_CP_SIZE, hci_request::rlen, and hci_request::rparam.
int hci_read_remote_name (int dd, const bdaddr_t * bdaddr, int len, char * name, int to)
Parameters
dd
bdaddr
len
name
to
Returns
Definition at line 2053 of file hci.c.
References hci_read_remote_name_with_clock_offset().
int hci_read_remote_name_cancel (int dd, const bdaddr_t * bdaddr, int to)
Parameters
dd
bdaddr
to
Returns
Definition at line 2068 of file hci.c.
References bacpy(), hci_request::clen, hci_request::cparam, hci_send_req(), hci_request::ocf, OCF_REMOTE_NAME_REQ_CANCEL, hci_request::ogf, OGF_LINK_CTL, and REMOTE_NAME_REQ_CANCEL_CP_SIZE.
int hci_read_remote_name_with_clock_offset (int dd, const bdaddr_t * bdaddr, uint8_t pscan_rep_mode, uint16_t clkoffset, int len, char * name, int to)
Parameters
dd
bdaddr
pscan_rep_mode
clkoffset
len
name
to
Returns
Definition at line 2007 of file hci.c.
References bacpy(), hci_request::clen, hci_request::cparam, hci_request::event, EVT_REMOTE_NAME_REQ_COMPLETE, EVT_REMOTE_NAME_REQ_COMPLETE_SIZE, hci_send_req(), hci_request::ocf, OCF_REMOTE_NAME_REQ, hci_request::ogf, OGF_LINK_CTL, REMOTE_NAME_REQ_CP_SIZE, hci_request::rlen, and hci_request::rparam.
Referenced by hci_read_remote_name().
int hci_read_remote_version (int dd, uint16_t handle, struct hci_version * ver, int to)
Parameters
dd
handle
ver
to
Returns
Definition at line 2097 of file hci.c.
References btohs, hci_request::clen, hci_request::cparam, hci_request::event, EVT_READ_REMOTE_VERSION_COMPLETE, EVT_READ_REMOTE_VERSION_COMPLETE_SIZE, hci_send_req(), hci_version::lmp_subver, hci_version::lmp_ver, hci_version::manufacturer, hci_request::ocf, OCF_READ_REMOTE_VERSION, hci_request::ogf, OGF_LINK_CTL, READ_REMOTE_VERSION_CP_SIZE, hci_request::rlen, and hci_request::rparam.
int hci_read_rssi (int dd, uint16_t handle, int8_t * rssi, int to)
Parameters
dd
handle
rssi
to
Returns
Definition at line 3630 of file hci.c.
References hci_request::clen, hci_request::cparam, hci_send_req(), hci_request::ocf, OCF_READ_RSSI, hci_request::ogf, OGF_STATUS_PARAM, READ_RSSI_RP_SIZE, hci_request::rlen, and hci_request::rparam.
int hci_read_simple_pairing_mode (int dd, uint8_t * mode, int to)
Parameters
dd
mode
to
Returns
Definition at line 3191 of file hci.c.
References hci_send_req(), hci_request::ocf, OCF_READ_SIMPLE_PAIRING_MODE, hci_request::ogf, OGF_HOST_CTL, READ_SIMPLE_PAIRING_MODE_RP_SIZE, hci_request::rlen, and hci_request::rparam.
int hci_read_stored_link_key (int dd, bdaddr_t * bdaddr, uint8_t all, int to)
Parameters
dd
bdaddr
all
to
Returns
Definition at line 2615 of file hci.c.
References bacpy(), hci_request::clen, hci_request::cparam, hci_send_req(), hci_request::ocf, OCF_READ_STORED_LINK_KEY, hci_request::ogf, OGF_HOST_CTL, and READ_STORED_LINK_KEY_CP_SIZE.
int hci_read_transmit_power_level (int dd, uint16_t handle, uint8_t type, int8_t * level, int to)
Parameters
dd
handle
type
level
to
Returns
Definition at line 3373 of file hci.c.
References hci_request::clen, hci_request::cparam, hci_send_req(), hci_request::ocf, OCF_READ_TRANSMIT_POWER_LEVEL, hci_request::ogf, OGF_HOST_CTL, READ_TRANSMIT_POWER_LEVEL_CP_SIZE, READ_TRANSMIT_POWER_LEVEL_RP_SIZE, hci_request::rlen, hci_request::rparam, and type.
int hci_read_voice_setting (int dd, uint16_t * vs, int to)
Parameters
dd
vs
to
Returns
Definition at line 2500 of file hci.c.
References hci_send_req(), hci_request::ocf, OCF_READ_VOICE_SETTING, hci_request::ogf, OGF_HOST_CTL, READ_VOICE_SETTING_RP_SIZE, hci_request::rlen, and hci_request::rparam.
char* hci_scoptypetostr (unsigned int ptype)
return the SCO (synchronous connection orientated) links string given the code
Parameters
ptype SCO type code
Returns
SCO string (NULL if error)
Definition at line 346 of file hci.c.
References hci_bit2str().
int hci_send_cmd (int dd, uint16_t ogf, uint16_t ocf, uint8_t plen, void * param)
Parameters
dd Device descriptor returned by hci_open_dev.
ogf
ocf
plen
param
Returns
Definition at line 1343 of file hci.c.
References cmd_opcode_pack, HCI_COMMAND_HDR_SIZE, HCI_COMMAND_PKT, htobs, and type.
Referenced by hci_send_req().
int hci_send_req (int dd, struct hci_request * r, int to)
Parameters
dd
r
to
Returns
Definition at line 1381 of file hci.c.
References bacmp(), hci_request::clen, cmd_opcode_pack, hci_request::cparam, hci_request::event, EVT_CMD_COMPLETE, EVT_CMD_COMPLETE_SIZE, EVT_CMD_STATUS, EVT_LE_META_EVENT, EVT_REMOTE_NAME_REQ_COMPLETE, HCI_EVENT_HDR_SIZE, HCI_EVENT_PKT, HCI_FILTER, hci_filter_clear(), hci_filter_set_event(), hci_filter_set_opcode(), hci_filter_set_ptype(), HCI_MAX_EVENT_SIZE, hci_send_cmd(), htobs, MIN, hci_request::ocf, hci_request::ogf, opcode, hci_request::rlen, hci_request::rparam, and SOL_HCI.
Referenced by hci_authenticate_link(), hci_change_link_key(), hci_create_connection(), hci_delete_stored_link_key(), hci_disconnect(), hci_encrypt_link(), hci_exit_park_mode(), hci_le_add_resolving_list(), hci_le_add_white_list(), hci_le_clear_resolving_list(), hci_le_clear_white_list(), hci_le_conn_update(), hci_le_create_conn(), hci_le_read_remote_features(), hci_le_read_resolving_list_size(), hci_le_read_white_list_size(), hci_le_rm_resolving_list(), hci_le_rm_white_list(), hci_le_set_address_resolution_enable(), hci_le_set_advertise_enable(), hci_le_set_scan_enable(), hci_le_set_scan_parameters(), hci_park_mode(), hci_read_afh_map(), hci_read_afh_mode(), hci_read_bd_addr(), hci_read_class_of_dev(), hci_read_clock(), hci_read_clock_offset(), hci_read_current_iac_lap(), hci_read_ext_inquiry_response(), hci_read_inq_response_tx_power_level(), hci_read_inquiry_mode(), hci_read_inquiry_scan_type(), hci_read_link_policy(), hci_read_link_quality(), hci_read_link_supervision_timeout(), hci_read_local_commands(), hci_read_local_ext_features(), hci_read_local_features(), hci_read_local_name(), hci_read_local_oob_data(), hci_read_local_version(), hci_read_remote_ext_features(), hci_read_remote_features(), hci_read_remote_name_cancel(), hci_read_remote_name_with_clock_offset(), hci_read_remote_version(), hci_read_rssi(), hci_read_simple_pairing_mode(), hci_read_stored_link_key(), hci_read_transmit_power_level(), hci_read_voice_setting(), hci_set_afh_classification(), hci_switch_role(), hci_write_afh_mode(), hci_write_class_of_dev(), hci_write_current_iac_lap(), hci_write_ext_inquiry_response(), hci_write_inquiry_mode(), hci_write_inquiry_scan_type(), hci_write_inquiry_transmit_power_level(), hci_write_link_policy(), hci_write_link_supervision_timeout(), hci_write_local_name(), hci_write_simple_pairing_mode(), hci_write_stored_link_key(), and hci_write_voice_setting().
int hci_set_afh_classification (int dd, uint8_t * map, int to)
Parameters
dd
map
to
Returns
Definition at line 3558 of file hci.c.
References hci_request::clen, hci_request::cparam, hci_send_req(), hci_request::ocf, OCF_SET_AFH_CLASSIFICATION, hci_request::ogf, OGF_HOST_CTL, hci_request::rlen, hci_request::rparam, SET_AFH_CLASSIFICATION_CP_SIZE, and SET_AFH_CLASSIFICATION_RP_SIZE.
static int hci_str2bit (hci_map * map, char * str, unsigned int * val) static
ored bits corresponding to comma separated commands matching the hci_map array
Parameters
map pointer to the hci_map array
str commands, separated by commas for match in the hci_map array
val ored bits (from the hci_map) of maching commands
Returns
1 val is set, 0
Definition at line 99 of file hci.c.
Referenced by hci_strtolm(), hci_strtolp(), hci_strtoptype(), and hci_strtoscoptype().
static int hci_str2uint (hci_map * map, char * str, unsigned int * val) static
lookup a command string in the hci_map array and return the corresponding code
Parameters
map pointer to the hci_map array
str command to match
val returned corresponding code
Returns
1 val is set 0 if no matching string
Definition at line 158 of file hci.c.
References hci_map::str, and hci_map::val.
Referenced by hci_strtover(), lmp_strtover(), and pal_strtover().
int hci_strtolm (char * str, unsigned int * val)
retrun Link mode mapping code given the tring
Parameters
str Link mode mapping string
val Link mode mapping code
Returns
1 match found, 0 error
Definition at line 443 of file hci.c.
References hci_str2bit().
int hci_strtolp (char * str, unsigned int * val)
return Link policy mapping code given the string
Parameters
str Link policy mapping string
val Link policy mapping code
Returns
1 match found 0 error
Definition at line 391 of file hci.c.
References hci_str2bit().
int hci_strtoptype (char * str, unsigned int * val)
return the HCI packet type code given the string
Parameters
str HCI packet type string
val HCI packet type code
Returns
1 if found 0 error
Definition at line 335 of file hci.c.
References hci_str2bit().
int hci_strtoscoptype (char * str, unsigned int * val)
return the SCO (synchronous connection orientated) links code given the string
Parameters
str SCO (synchronous connection orientated) links string
val SCO (synchronous connection orientated) links code
Returns
1 match found 0 error
Definition at line 358 of file hci.c.
References hci_str2bit().
int hci_strtover (char * str, unsigned int * ver)
return the version code given the string
Parameters
str version string
ver version code
Returns
1 of match found, 0 error
Definition at line 809 of file hci.c.
References hci_str2uint().
int hci_switch_role (int dd, bdaddr_t * bdaddr, uint8_t role, int to)
Parameters
dd
bdaddr
role
to
Returns
Definition at line 2804 of file hci.c.
References bacpy(), hci_request::clen, hci_request::cparam, hci_request::event, EVT_ROLE_CHANGE, EVT_ROLE_CHANGE_SIZE, hci_send_req(), hci_request::ocf, OCF_SWITCH_ROLE, hci_request::ogf, OGF_LINK_POLICY, hci_request::rlen, hci_request::rparam, and SWITCH_ROLE_CP_SIZE.
char* hci_typetostr (int type)
return the bluetooth type string give the code (see HCI controller types in hci.h)
Parameters
type HCI controller types
Returns
corresponding string (NULL if error)
Definition at line 228 of file hci.c.
References HCI_AMP, and HCI_BREDR.
static char* hci_uint2str (hci_map * m, unsigned int val) static
lookup the hci_map and find entry corresponding to val and return the corresponding string
Parameters
m hci_map pointer
val val to match in the hci_map
Returns
string mapped to the matching value or NULL if no matching
Definition at line 130 of file hci.c.
References hci_map::str, and hci_map::val.
Referenced by hci_cmdtostr(), hci_vertostr(), lmp_vertostr(), and pal_vertostr().
char* hci_vertostr (unsigned int ver)
translate a version code into a mapping string
Parameters
ver version code
Returns
mapping string (NULL if error)
Definition at line 797 of file hci.c.
References hci_uint2str().
int hci_write_afh_mode (int dd, uint8_t mode, int to)
Parameters
dd
mode
to
Returns
Definition at line 3083 of file hci.c.
References hci_request::clen, hci_request::cparam, hci_send_req(), hci_request::ocf, OCF_WRITE_AFH_MODE, hci_request::ogf, OGF_HOST_CTL, hci_request::rlen, hci_request::rparam, WRITE_AFH_MODE_CP_SIZE, and WRITE_AFH_MODE_RP_SIZE.
int hci_write_class_of_dev (int dd, uint32_t cls, int to)
Parameters
dd
cls
to
Returns
Definition at line 2476 of file hci.c.
References hci_request::clen, hci_request::cparam, hci_send_req(), hci_request::ocf, OCF_WRITE_CLASS_OF_DEV, hci_request::ogf, OGF_HOST_CTL, and WRITE_CLASS_OF_DEV_CP_SIZE.
int hci_write_current_iac_lap (int dd, uint8_t num_iac, uint8_t * lap, int to)
Parameters
dd
num_iac
lap
to
Returns
Definition at line 2588 of file hci.c.
References hci_request::clen, hci_request::cparam, hci_send_req(), hci_request::ocf, OCF_WRITE_CURRENT_IAC_LAP, hci_request::ogf, and OGF_HOST_CTL.
int hci_write_ext_inquiry_response (int dd, uint8_t fec, uint8_t * data, int to)
Parameters
dd
fec
data
to
Returns
Definition at line 3154 of file hci.c.
References hci_request::clen, hci_request::cparam, HCI_MAX_EIR_LENGTH, hci_send_req(), hci_request::ocf, OCF_WRITE_EXT_INQUIRY_RESPONSE, hci_request::ogf, OGF_HOST_CTL, hci_request::rlen, hci_request::rparam, WRITE_EXT_INQUIRY_RESPONSE_CP_SIZE, and WRITE_EXT_INQUIRY_RESPONSE_RP_SIZE.
int hci_write_inquiry_mode (int dd, uint8_t mode, int to)
Parameters
dd
mode
to
Returns
Definition at line 3016 of file hci.c.
References hci_request::clen, hci_request::cparam, hci_send_req(), hci_request::ocf, OCF_WRITE_INQUIRY_MODE, hci_request::ogf, OGF_HOST_CTL, hci_request::rlen, hci_request::rparam, WRITE_INQUIRY_MODE_CP_SIZE, and WRITE_INQUIRY_MODE_RP_SIZE.
int hci_write_inquiry_scan_type (int dd, uint8_t type, int to)
Parameters
dd
type
to
Returns
Definition at line 2949 of file hci.c.
References hci_request::clen, hci_request::cparam, hci_send_req(), hci_request::ocf, OCF_WRITE_INQUIRY_SCAN_TYPE, hci_request::ogf, OGF_HOST_CTL, hci_request::rlen, hci_request::rparam, type, WRITE_INQUIRY_SCAN_TYPE_CP_SIZE, and WRITE_INQUIRY_SCAN_TYPE_RP_SIZE.
int hci_write_inquiry_transmit_power_level (int dd, int8_t level, int to)
Parameters
dd
level
to
Returns
Definition at line 3335 of file hci.c.
References hci_request::clen, hci_request::cparam, hci_send_req(), hci_request::ocf, OCF_WRITE_INQUIRY_TRANSMIT_POWER_LEVEL, hci_request::ogf, OGF_HOST_CTL, hci_request::rlen, hci_request::rparam, WRITE_INQUIRY_TRANSMIT_POWER_LEVEL_CP_SIZE, and WRITE_INQUIRY_TRANSMIT_POWER_LEVEL_RP_SIZE.
int hci_write_link_policy (int dd, uint16_t handle, uint16_t policy, int to)
Parameters
dd
handle
policy
to
Returns
Definition at line 3447 of file hci.c.
References hci_request::clen, hci_request::cparam, hci_send_req(), hci_request::ocf, OCF_WRITE_LINK_POLICY, hci_request::ogf, OGF_LINK_POLICY, hci_request::rlen, hci_request::rparam, WRITE_LINK_POLICY_CP_SIZE, and WRITE_LINK_POLICY_RP_SIZE.
int hci_write_link_supervision_timeout (int dd, uint16_t handle, uint16_t timeout, int to)
Parameters
dd
handle
timeout
to
Returns
Definition at line 3520 of file hci.c.
References hci_request::clen, hci_request::cparam, hci_send_req(), hci_request::ocf, OCF_WRITE_LINK_SUPERVISION_TIMEOUT, hci_request::ogf, OGF_HOST_CTL, hci_request::rlen, hci_request::rparam, WRITE_LINK_SUPERVISION_TIMEOUT_CP_SIZE, and WRITE_LINK_SUPERVISION_TIMEOUT_RP_SIZE.
int hci_write_local_name (int dd, const char * name, int to)
Parameters
dd
name
to
Returns
Definition at line 1975 of file hci.c.
References CHANGE_LOCAL_NAME_CP_SIZE, hci_request::clen, hci_request::cparam, hci_send_req(), hci_request::ocf, OCF_CHANGE_LOCAL_NAME, hci_request::ogf, and OGF_HOST_CTL.
int hci_write_simple_pairing_mode (int dd, uint8_t mode, int to)
Parameters
dd
mode
to
Returns
Definition at line 3222 of file hci.c.
References hci_request::clen, hci_request::cparam, hci_send_req(), hci_request::ocf, OCF_WRITE_SIMPLE_PAIRING_MODE, hci_request::ogf, OGF_HOST_CTL, hci_request::rlen, hci_request::rparam, WRITE_SIMPLE_PAIRING_MODE_CP_SIZE, and WRITE_SIMPLE_PAIRING_MODE_RP_SIZE.
int hci_write_stored_link_key (int dd, bdaddr_t * bdaddr, uint8_t * key, int to)
Parameters
dd
bdaddr
key
to
Returns
Definition at line 2642 of file hci.c.
References bacpy(), hci_request::clen, hci_request::cparam, hci_send_req(), hci_request::ocf, OCF_WRITE_STORED_LINK_KEY, hci_request::ogf, OGF_HOST_CTL, and WRITE_STORED_LINK_KEY_CP_SIZE.
int hci_write_voice_setting (int dd, uint16_t vs, int to)
Parameters
dd
vs
to
Returns
Definition at line 2531 of file hci.c.
References hci_request::clen, hci_request::cparam, hci_send_req(), hci_request::ocf, OCF_WRITE_VOICE_SETTING, hci_request::ogf, OGF_HOST_CTL, and WRITE_VOICE_SETTING_CP_SIZE.
char* lmp_featurestostr (uint8_t * features, char * pref, int width)
Link Manager Protocol feature string given code
Parameters
features Link Manager Protocol feature code
pref prefix
width
Returns
Link Manager Protocol string or NULL if error
Definition at line 962 of file hci.c.
References bt_malloc(), hci_map::str, and hci_map::val.
int lmp_strtover (char * str, unsigned int * ver)
Link Manager Protocol code given the string
Parameters
str version string
ver version code
Returns
1 of match found, 0 error
Definition at line 832 of file hci.c.
References hci_str2uint().
char* lmp_vertostr (unsigned int ver)
Link Manager Protocol version (same as hci) string given the code
Parameters
ver version code
Returns
mapping string (NULL if error)
Definition at line 820 of file hci.c.
References hci_uint2str().
int pal_strtover (char * str, unsigned int * ver)
pal version code given string
Parameters
str pal version string
ver pal version code
Returns
1 pal version code is set 0 error
Definition at line 860 of file hci.c.
References hci_str2uint().
char* pal_vertostr (unsigned int ver)
pal version string given code
Parameters
ver pal version code
Returns
pal version string or NULL if error
Definition at line 848 of file hci.c.
References hci_uint2str().
Variable Documentation
hci_map commands_map[] static
Definition at line 449 of file hci.c.
Referenced by hci_commandstostr().
hci_map dev_flags_map[] static
Initial value:
= {
    { "UP",      HCI_UP      },
    { "INIT",    HCI_INIT    },
    { "RUNNING", HCI_RUNNING },
    { "RAW",     HCI_RAW     },
    { "PSCAN",   HCI_PSCAN   },
    { "ISCAN",   HCI_ISCAN   },
    { "INQUIRY", HCI_INQUIRY },
    { "AUTH",    HCI_AUTH    },
    { "ENCRYPT", HCI_ENCRYPT },
    { NULL }
}
Definition at line 241 of file hci.c.
Referenced by hci_dflagstostr().
hci_map link_mode_map[] static
Initial value:
= {
    { "NONE",   0       },
    { "ACCEPT", HCI_LM_ACCEPT   },
    { "MASTER", HCI_LM_MASTER   },
    { "AUTH",   HCI_LM_AUTH },
    { "ENCRYPT",    HCI_LM_ENCRYPT  },
    { "TRUSTED",    HCI_LM_TRUSTED  },
    { "RELIABLE",   HCI_LM_RELIABLE },
    { "SECURE", HCI_LM_SECURE   },
    { NULL }
}
Definition at line 397 of file hci.c.
hci_map link_policy_map[] static
Initial value:
= {
    { "NONE",   0       },
    { "RSWITCH",    HCI_LP_RSWITCH  },
    { "HOLD",   HCI_LP_HOLD },
    { "SNIFF",  HCI_LP_SNIFF    },
    { "PARK",   HCI_LP_PARK },
    { NULL }
}
Definition at line 364 of file hci.c.
hci_map lmp_features_map[8][9] static
Definition at line 866 of file hci.c.
hci_map pal_map[] static
Initial value:
= {
    { "3.0",    0x01 },
    { NULL }
}
Definition at line 837 of file hci.c.
hci_map pkt_type_map[] static
Initial value:
= {
    { "DM1",   HCI_DM1  },
    { "DM3",   HCI_DM3  },
    { "DM5",   HCI_DM5  },
    { "DH1",   HCI_DH1  },
    { "DH3",   HCI_DH3  },
    { "DH5",   HCI_DH5  },
    { "HV1",   HCI_HV1  },
    { "HV2",   HCI_HV2  },
    { "HV3",   HCI_HV3  },
    { "2-DH1", HCI_2DH1 },
    { "2-DH3", HCI_2DH3 },
    { "2-DH5", HCI_2DH5 },
    { "3-DH1", HCI_3DH1 },
    { "3-DH3", HCI_3DH3 },
    { "3-DH5", HCI_3DH5 },
    { NULL }
}
Definition at line 283 of file hci.c.
hci_map sco_ptype_map[] static
Initial value:
= {
    { "HV1",   0x0001   },
    { "HV2",   0x0002   },
    { "HV3",   0x0004   },
    { "EV3",   HCI_EV3  },
    { "EV4",   HCI_EV4  },
    { "EV5",   HCI_EV5  },
    { "2-EV3", HCI_2EV3 },
    { "2-EV5", HCI_2EV5 },
    { "3-EV3", HCI_3EV3 },
    { "3-EV5", HCI_3EV5 },
    { NULL }
}
Definition at line 303 of file hci.c.
hci_map ver_map[] static
Initial value:
= {
    { "1.0b",   0x00 },
    { "1.1",    0x01 },
    { "1.2",    0x02 },
    { "2.0",    0x03 },
    { "2.1",    0x04 },
    { "3.0",    0x05 },
    { "4.0",    0x06 },
    { "4.1",    0x07 },
    { "4.2",    0x08 },
    { NULL }
}
Definition at line 778 of file hci.c.