ble_gatt_client: src/crypto.c File Reference
crypto.c File Reference
crypting gatt messages
#include <fcntl.h>
#include <unistd.h>
#include <string.h>
#include <sys/socket.h>
#include "util.h"
#include "crypto.h"
Data Structures
struct sockaddr_alg
struct af_alg_iv
struct bt_crypto
struct u128
Macros
#define ALG_SET_KEY 1
#define ALG_SET_IV 2
#define ALG_SET_OP 3
#define ALG_OP_DECRYPT 0
#define ALG_OP_ENCRYPT 1
#define PF_ALG 38 /* Algorithm sockets. */
#define AF_ALG PF_ALG
#define SOL_ALG 279
#define CMAC_MSG_MAX 80
Typedefs
typedef uint8_t __u8
typedef uint16_t __u16
typedef uint32_t __u32
Functions
static int urandom_setup (void)
static int ecb_aes_setup (void)
static int cmac_aes_setup (void)
struct bt_crypto * bt_crypto_new (void)
struct bt_crypto * bt_crypto_ref (struct bt_crypto *crypto)
void bt_crypto_unref (struct bt_crypto *crypto)
bool bt_crypto_random_bytes (struct bt_crypto *crypto, uint8_t *buf, uint8_t num_bytes)
static int alg_new (int fd, const void *keyval, socklen_t keylen)
static bool alg_encrypt (int fd, const void *inbuf, size_t inlen, void *outbuf, size_t outlen)
static void swap_buf (const uint8_t *src, uint8_t *dst, uint16_t len)
bool bt_crypto_sign_att (struct bt_crypto *crypto, const uint8_t key[16], const uint8_t *m, uint16_t m_len, uint32_t sign_cnt, uint8_t signature[12])
bool bt_crypto_e (struct bt_crypto *crypto, const uint8_t key[16], const uint8_t plaintext[16], uint8_t encrypted[16])
bool bt_crypto_ah (struct bt_crypto *crypto, const uint8_t k[16], const uint8_t r[3], uint8_t hash[3])
static void u128_xor (const uint8_t p[16], const uint8_t q[16], uint8_t r[16])
bool bt_crypto_c1 (struct bt_crypto *crypto, const uint8_t k[16], const uint8_t r[16], const uint8_t pres[7], const uint8_t preq[7], uint8_t iat, const uint8_t ia[6], uint8_t rat, const uint8_t ra[6], uint8_t res[16])
bool bt_crypto_s1 (struct bt_crypto *crypto, const uint8_t k[16], const uint8_t r1[16], const uint8_t r2[16], uint8_t res[16])
static bool aes_cmac (struct bt_crypto *crypto, uint8_t key[16], uint8_t *msg, size_t msg_len, uint8_t res[16])
bool bt_crypto_f4 (struct bt_crypto *crypto, uint8_t u[32], uint8_t v[32], uint8_t x[16], uint8_t z, uint8_t res[16])
bool bt_crypto_f5 (struct bt_crypto *crypto, uint8_t w[32], uint8_t n1[16], uint8_t n2[16], uint8_t a1[7], uint8_t a2[7], uint8_t mackey[16], uint8_t ltk[16])
bool bt_crypto_f6 (struct bt_crypto *crypto, uint8_t w[16], uint8_t n1[16], uint8_t n2[16], uint8_t r[16], uint8_t io_cap[3], uint8_t a1[7], uint8_t a2[7], uint8_t res[16])
bool bt_crypto_g2 (struct bt_crypto *crypto, uint8_t u[32], uint8_t v[32], uint8_t x[16], uint8_t y[16], uint32_t *val)
Detailed Description
crypting gatt messages
Author
Gilbert Brault
Copyright
Gilbert Brault 2015 the original work comes from bluez v5.39 value add: documenting main features
Definition in file crypto.c.
Macro Definition Documentation
#define AF_ALG PF_ALG
Definition at line 75 of file crypto.c.
Referenced by cmac_aes_setup(), and ecb_aes_setup().
#define ALG_OP_DECRYPT 0
Definition at line 71 of file crypto.c.
#define ALG_OP_ENCRYPT 1
Definition at line 72 of file crypto.c.
Referenced by alg_encrypt().
#define ALG_SET_IV 2
Definition at line 68 of file crypto.c.
#define ALG_SET_KEY 1
Definition at line 67 of file crypto.c.
Referenced by alg_new().
#define ALG_SET_OP 3
Definition at line 69 of file crypto.c.
Referenced by alg_encrypt().
#define CMAC_MSG_MAX 80
Definition at line 85 of file crypto.c.
Referenced by aes_cmac().
#define PF_ALG 38 /* Algorithm sockets. */
Definition at line 74 of file crypto.c.
Referenced by cmac_aes_setup(), and ecb_aes_setup().
#define SOL_ALG 279
Definition at line 81 of file crypto.c.
Referenced by alg_encrypt(), and alg_new().
Typedef Documentation
typedef uint16_t __u16
Definition at line 48 of file crypto.c.
typedef uint32_t __u32
Definition at line 49 of file crypto.c.
typedef uint8_t __u8
Definition at line 47 of file crypto.c.
Function Documentation
static bool aes_cmac (struct bt_crypto * crypto, uint8_t key[16], uint8_t * msg, size_t msg_len, uint8_t res[16]) static
Definition at line 582 of file crypto.c.
References alg_new(), bt_crypto::cmac_aes, CMAC_MSG_MAX, and swap_buf().
Referenced by bt_crypto_f4(), bt_crypto_f5(), bt_crypto_f6(), and bt_crypto_g2().
static bool alg_encrypt (int fd, const void * inbuf, size_t inlen, void * outbuf, size_t outlen) static
Definition at line 230 of file crypto.c.
References ALG_OP_ENCRYPT, ALG_SET_OP, and SOL_ALG.
Referenced by bt_crypto_e().
static int alg_new (int fd, const void * keyval, socklen_t keylen) static
Definition at line 221 of file crypto.c.
References ALG_SET_KEY, and SOL_ALG.
Referenced by aes_cmac(), bt_crypto_e(), and bt_crypto_sign_att().
bool bt_crypto_ah (struct bt_crypto * crypto, const uint8_t k[16], const uint8_t r[3], uint8_t hash[3])
Definition at line 415 of file crypto.c.
References bt_crypto_e().
bool bt_crypto_c1 (struct bt_crypto * crypto, const uint8_t k[16], const uint8_t r[16], const uint8_t pres[7], const uint8_t preq[7], uint8_t iat, const uint8_t ia[6], uint8_t rat, const uint8_t ra[6], uint8_t res[16])
Definition at line 508 of file crypto.c.
References bt_crypto_e(), and u128_xor().
bool bt_crypto_e (struct bt_crypto * crypto, const uint8_t key[16], const uint8_t plaintext[16], uint8_t encrypted[16])
Definition at line 350 of file crypto.c.
References alg_encrypt(), alg_new(), bt_crypto::ecb_aes, and swap_buf().
Referenced by bt_crypto_ah(), bt_crypto_c1(), and bt_crypto_s1().
bool bt_crypto_f4 (struct bt_crypto * crypto, uint8_t u[32], uint8_t v[32], uint8_t x[16], uint8_t z, uint8_t res[16])
Definition at line 617 of file crypto.c.
References aes_cmac().
bool bt_crypto_f5 (struct bt_crypto * crypto, uint8_t w[32], uint8_t n1[16], uint8_t n2[16], uint8_t a1[7], uint8_t a2[7], uint8_t mackey[16], uint8_t ltk[16])
Definition at line 632 of file crypto.c.
References aes_cmac().
bool bt_crypto_f6 (struct bt_crypto * crypto, uint8_t w[16], uint8_t n1[16], uint8_t n2[16], uint8_t r[16], uint8_t io_cap[3], uint8_t a1[7], uint8_t a2[7], uint8_t res[16])
Definition at line 660 of file crypto.c.
References aes_cmac().
bool bt_crypto_g2 (struct bt_crypto * crypto, uint8_t u[32], uint8_t v[32], uint8_t x[16], uint8_t y[16], uint32_t * val)
Definition at line 676 of file crypto.c.
References aes_cmac(), and get_le32().
struct bt_crypto* bt_crypto_new (void)
Definition at line 149 of file crypto.c.
References bt_crypto_ref(), bt_crypto::cmac_aes, cmac_aes_setup(), bt_crypto::ecb_aes, ecb_aes_setup(), new0, bt_crypto::urandom, and urandom_setup().
Referenced by bt_att_new().
bool bt_crypto_random_bytes (struct bt_crypto * crypto, uint8_t * buf, uint8_t num_bytes)
Definition at line 206 of file crypto.c.
References bt_crypto::urandom.
struct bt_crypto* bt_crypto_ref (struct bt_crypto * crypto)
Definition at line 181 of file crypto.c.
References bt_crypto::ref_count.
Referenced by bt_crypto_new().
bool bt_crypto_s1 (struct bt_crypto * crypto, const uint8_t k[16], const uint8_t r1[16], const uint8_t r2[16], uint8_t res[16])
Definition at line 572 of file crypto.c.
References bt_crypto_e().
bool bt_crypto_sign_att (struct bt_crypto * crypto, const uint8_t key[16], const uint8_t * m, uint16_t m_len, uint32_t sign_cnt, uint8_t signature[12])
Definition at line 277 of file crypto.c.
References alg_new(), bt_crypto::cmac_aes, put_be32(), put_le32(), and swap_buf().
Referenced by encode_pdu(), and handle_signed().
void bt_crypto_unref (struct bt_crypto * crypto)
Definition at line 191 of file crypto.c.
References bt_crypto::cmac_aes, bt_crypto::ecb_aes, bt_crypto::ref_count, and bt_crypto::urandom.
Referenced by bt_att_free().
static int cmac_aes_setup (void) static
Definition at line 127 of file crypto.c.
References AF_ALG, PF_ALG, sockaddr_alg::salg_family, sockaddr_alg::salg_name, and sockaddr_alg::salg_type.
Referenced by bt_crypto_new().
static int ecb_aes_setup (void) static
Definition at line 105 of file crypto.c.
References AF_ALG, PF_ALG, sockaddr_alg::salg_family, sockaddr_alg::salg_name, and sockaddr_alg::salg_type.
Referenced by bt_crypto_new().
static void swap_buf (const uint8_t * src, uint8_t * dst, uint16_t len) inline static
Definition at line 269 of file crypto.c.
Referenced by aes_cmac(), bt_crypto_e(), and bt_crypto_sign_att().
static void u128_xor (const uint8_t p[16], const uint8_t q[16], uint8_t r[16]) inline static
Definition at line 442 of file crypto.c.
References u128::a, and u128::b.
Referenced by bt_crypto_c1().
static int urandom_setup (void) static
Definition at line 94 of file crypto.c.
Referenced by bt_crypto_new().