ble_gatt_client: src/crypto.h File Reference
crypto.h File Reference
#include <stdbool.h>
#include <stdint.h>
Functions
struct bt_crypto * bt_crypto_new (void)
struct bt_crypto * bt_crypto_ref (struct bt_crypto *crypto)
void bt_crypto_unref (struct bt_crypto *crypto)
bool bt_crypto_random_bytes (struct bt_crypto *crypto, uint8_t *buf, uint8_t num_bytes)
bool bt_crypto_e (struct bt_crypto *crypto, const uint8_t key[16], const uint8_t plaintext[16], uint8_t encrypted[16])
bool bt_crypto_ah (struct bt_crypto *crypto, const uint8_t k[16], const uint8_t r[3], uint8_t hash[3])
bool bt_crypto_c1 (struct bt_crypto *crypto, const uint8_t k[16], const uint8_t r[16], const uint8_t pres[7], const uint8_t preq[7], uint8_t iat, const uint8_t ia[6], uint8_t rat, const uint8_t ra[6], uint8_t res[16])
bool bt_crypto_s1 (struct bt_crypto *crypto, const uint8_t k[16], const uint8_t r1[16], const uint8_t r2[16], uint8_t res[16])
bool bt_crypto_f4 (struct bt_crypto *crypto, uint8_t u[32], uint8_t v[32], uint8_t x[16], uint8_t z, uint8_t res[16])
bool bt_crypto_f5 (struct bt_crypto *crypto, uint8_t w[32], uint8_t n1[16], uint8_t n2[16], uint8_t a1[7], uint8_t a2[7], uint8_t mackey[16], uint8_t ltk[16])
bool bt_crypto_f6 (struct bt_crypto *crypto, uint8_t w[16], uint8_t n1[16], uint8_t n2[16], uint8_t r[16], uint8_t io_cap[3], uint8_t a1[7], uint8_t a2[7], uint8_t res[16])
bool bt_crypto_g2 (struct bt_crypto *crypto, uint8_t u[32], uint8_t v[32], uint8_t x[16], uint8_t y[16], uint32_t *val)
bool bt_crypto_sign_att (struct bt_crypto *crypto, const uint8_t key[16], const uint8_t *m, uint16_t m_len, uint32_t sign_cnt, uint8_t signature[12])
Function Documentation
bool bt_crypto_ah (struct bt_crypto * crypto, const uint8_t k[16], const uint8_t r[3], uint8_t hash[3])
Definition at line 415 of file crypto.c.
References bt_crypto_e().
bool bt_crypto_c1 (struct bt_crypto * crypto, const uint8_t k[16], const uint8_t r[16], const uint8_t pres[7], const uint8_t preq[7], uint8_t iat, const uint8_t ia[6], uint8_t rat, const uint8_t ra[6], uint8_t res[16])
Definition at line 508 of file crypto.c.
References bt_crypto_e(), and u128_xor().
bool bt_crypto_e (struct bt_crypto * crypto, const uint8_t key[16], const uint8_t plaintext[16], uint8_t encrypted[16])
Definition at line 350 of file crypto.c.
References alg_encrypt(), alg_new(), bt_crypto::ecb_aes, and swap_buf().
Referenced by bt_crypto_ah(), bt_crypto_c1(), and bt_crypto_s1().
bool bt_crypto_f4 (struct bt_crypto * crypto, uint8_t u[32], uint8_t v[32], uint8_t x[16], uint8_t z, uint8_t res[16])
Definition at line 617 of file crypto.c.
References aes_cmac().
bool bt_crypto_f5 (struct bt_crypto * crypto, uint8_t w[32], uint8_t n1[16], uint8_t n2[16], uint8_t a1[7], uint8_t a2[7], uint8_t mackey[16], uint8_t ltk[16])
Definition at line 632 of file crypto.c.
References aes_cmac().
bool bt_crypto_f6 (struct bt_crypto * crypto, uint8_t w[16], uint8_t n1[16], uint8_t n2[16], uint8_t r[16], uint8_t io_cap[3], uint8_t a1[7], uint8_t a2[7], uint8_t res[16])
Definition at line 660 of file crypto.c.
References aes_cmac().
bool bt_crypto_g2 (struct bt_crypto * crypto, uint8_t u[32], uint8_t v[32], uint8_t x[16], uint8_t y[16], uint32_t * val)
Definition at line 676 of file crypto.c.
References aes_cmac(), and get_le32().
struct bt_crypto* bt_crypto_new (void)
Definition at line 149 of file crypto.c.
References bt_crypto_ref(), bt_crypto::cmac_aes, cmac_aes_setup(), bt_crypto::ecb_aes, ecb_aes_setup(), new0, bt_crypto::urandom, and urandom_setup().
Referenced by bt_att_new().
bool bt_crypto_random_bytes (struct bt_crypto * crypto, uint8_t * buf, uint8_t num_bytes)
Definition at line 206 of file crypto.c.
References bt_crypto::urandom.
struct bt_crypto* bt_crypto_ref (struct bt_crypto * crypto)
Definition at line 181 of file crypto.c.
References bt_crypto::ref_count.
Referenced by bt_crypto_new().
bool bt_crypto_s1 (struct bt_crypto * crypto, const uint8_t k[16], const uint8_t r1[16], const uint8_t r2[16], uint8_t res[16])
Definition at line 572 of file crypto.c.
References bt_crypto_e().
bool bt_crypto_sign_att (struct bt_crypto * crypto, const uint8_t key[16], const uint8_t * m, uint16_t m_len, uint32_t sign_cnt, uint8_t signature[12])
Definition at line 277 of file crypto.c.
References alg_new(), bt_crypto::cmac_aes, put_be32(), put_le32(), and swap_buf().
Referenced by encode_pdu(), and handle_signed().
void bt_crypto_unref (struct bt_crypto * crypto)
Definition at line 191 of file crypto.c.
References bt_crypto::cmac_aes, bt_crypto::ecb_aes, bt_crypto::ref_count, and bt_crypto::urandom.
Referenced by bt_att_free().