ble_gatt_client: src/gatt-db.h File Reference
gatt-db.h File Reference
Typedefs
typedef void(* gatt_db_read_t)(struct gatt_db_attribute *attrib, unsigned int id, uint16_t offset, uint8_t opcode, struct bt_att *att, void *user_data)
typedef void(* gatt_db_write_t)(struct gatt_db_attribute *attrib, unsigned int id, uint16_t offset, const uint8_t *value, size_t len, uint8_t opcode, struct bt_att *att, void *user_data)
typedef void(* gatt_db_attribute_cb_t)(struct gatt_db_attribute *attrib, void *user_data)
typedef void(* gatt_db_destroy_func_t)(void *user_data)
typedef void(* gatt_db_attribute_read_t)(struct gatt_db_attribute *attrib, int err, const uint8_t *value, size_t length, void *user_data)
typedef void(* gatt_db_attribute_write_t)(struct gatt_db_attribute *attrib, int err, void *user_data)
Functions
struct gatt_db * gatt_db_new (void)
struct gatt_db * gatt_db_ref (struct gatt_db *db)
void gatt_db_unref (struct gatt_db *db)
bool gatt_db_isempty (struct gatt_db *db)
struct gatt_db_attribute * gatt_db_add_service (struct gatt_db *db, const bt_uuid_t *uuid, bool primary, uint16_t num_handles)
bool gatt_db_remove_service (struct gatt_db *db, struct gatt_db_attribute *attrib)
bool gatt_db_clear (struct gatt_db *db)
bool gatt_db_clear_range (struct gatt_db *db, uint16_t start_handle, uint16_t end_handle)
struct gatt_db_attribute * gatt_db_insert_service (struct gatt_db *db, uint16_t handle, const bt_uuid_t *uuid, bool primary, uint16_t num_handles)
struct gatt_db_attribute * gatt_db_service_add_characteristic (struct gatt_db_attribute *attrib, const bt_uuid_t *uuid, uint32_t permissions, uint8_t properties, gatt_db_read_t read_func, gatt_db_write_t write_func, void *user_data)
struct gatt_db_attribute * gatt_db_service_insert_characteristic (struct gatt_db_attribute *attrib, uint16_t handle, const bt_uuid_t *uuid, uint32_t permissions, uint8_t properties, gatt_db_read_t read_func, gatt_db_write_t write_func, void *user_data)
struct gatt_db_attribute * gatt_db_service_add_descriptor (struct gatt_db_attribute *attrib, const bt_uuid_t *uuid, uint32_t permissions, gatt_db_read_t read_func, gatt_db_write_t write_func, void *user_data)
struct gatt_db_attribute * gatt_db_service_insert_descriptor (struct gatt_db_attribute *attrib, uint16_t handle, const bt_uuid_t *uuid, uint32_t permissions, gatt_db_read_t read_func, gatt_db_write_t write_func, void *user_data)
struct gatt_db_attribute * gatt_db_service_add_included (struct gatt_db_attribute *attrib, struct gatt_db_attribute *include)
bool gatt_db_service_set_active (struct gatt_db_attribute *attrib, bool active)
bool gatt_db_service_get_active (struct gatt_db_attribute *attrib)
bool gatt_db_service_set_claimed (struct gatt_db_attribute *attrib, bool claimed)
bool gatt_db_service_get_claimed (struct gatt_db_attribute *attrib)
void gatt_db_read_by_group_type (struct gatt_db *db, uint16_t start_handle, uint16_t end_handle, const bt_uuid_t type, struct queue *queue)
unsigned int gatt_db_find_by_type (struct gatt_db *db, uint16_t start_handle, uint16_t end_handle, const bt_uuid_t *type, gatt_db_attribute_cb_t func, void *user_data)
unsigned int gatt_db_find_by_type_value (struct gatt_db *db, uint16_t start_handle, uint16_t end_handle, const bt_uuid_t *type, const void *value, size_t value_len, gatt_db_attribute_cb_t func, void *user_data)
void gatt_db_read_by_type (struct gatt_db *db, uint16_t start_handle, uint16_t end_handle, const bt_uuid_t type, struct queue *queue)
void gatt_db_find_information (struct gatt_db *db, uint16_t start_handle, uint16_t end_handle, struct queue *queue)
void gatt_db_foreach_service (struct gatt_db *db, const bt_uuid_t *uuid, gatt_db_attribute_cb_t func, void *user_data)
void gatt_db_foreach_service_in_range (struct gatt_db *db, const bt_uuid_t *uuid, gatt_db_attribute_cb_t func, void *user_data, uint16_t start_handle, uint16_t end_handle)
void gatt_db_service_foreach (struct gatt_db_attribute *attrib, const bt_uuid_t *uuid, gatt_db_attribute_cb_t func, void *user_data)
void gatt_db_service_foreach_char (struct gatt_db_attribute *attrib, gatt_db_attribute_cb_t func, void *user_data)
void gatt_db_service_foreach_desc (struct gatt_db_attribute *attrib, gatt_db_attribute_cb_t func, void *user_data)
void gatt_db_service_foreach_incl (struct gatt_db_attribute *attrib, gatt_db_attribute_cb_t func, void *user_data)
unsigned int gatt_db_register (struct gatt_db *db, gatt_db_attribute_cb_t service_added, gatt_db_attribute_cb_t service_removed, void *user_data, gatt_db_destroy_func_t destroy)
bool gatt_db_unregister (struct gatt_db *db, unsigned int id)
struct gatt_db_attribute * gatt_db_get_attribute (struct gatt_db *db, uint16_t handle)
struct gatt_db_attribute * gatt_db_get_service_with_uuid (struct gatt_db *db, const bt_uuid_t *uuid)
const bt_uuid_t * gatt_db_attribute_get_type (const struct gatt_db_attribute *attrib)
uint16_t gatt_db_attribute_get_handle (const struct gatt_db_attribute *attrib)
bool gatt_db_attribute_get_service_uuid (const struct gatt_db_attribute *attrib, bt_uuid_t *uuid)
bool gatt_db_attribute_get_service_handles (const struct gatt_db_attribute *attrib, uint16_t *start_handle, uint16_t *end_handle)
bool gatt_db_attribute_get_service_data (const struct gatt_db_attribute *attrib, uint16_t *start_handle, uint16_t *end_handle, bool *primary, bt_uuid_t *uuid)
bool gatt_db_attribute_get_char_data (const struct gatt_db_attribute *attrib, uint16_t *handle, uint16_t *value_handle, uint8_t *properties, bt_uuid_t *uuid)
bool gatt_db_attribute_get_incl_data (const struct gatt_db_attribute *attrib, uint16_t *handle, uint16_t *start_handle, uint16_t *end_handle)
uint32_t gatt_db_attribute_get_permissions (const struct gatt_db_attribute *attrib)
bool gatt_db_attribute_read (struct gatt_db_attribute *attrib, uint16_t offset, uint8_t opcode, struct bt_att *att, gatt_db_attribute_read_t func, void *user_data)
bool gatt_db_attribute_read_result (struct gatt_db_attribute *attrib, unsigned int id, int err, const uint8_t *value, size_t length)
bool gatt_db_attribute_write (struct gatt_db_attribute *attrib, uint16_t offset, const uint8_t *value, size_t len, uint8_t opcode, struct bt_att *att, gatt_db_attribute_write_t func, void *user_data)
bool gatt_db_attribute_write_result (struct gatt_db_attribute *attrib, unsigned int id, int err)
bool gatt_db_attribute_reset (struct gatt_db_attribute *attrib)
Typedef Documentation
typedef void(* gatt_db_attribute_cb_t)(struct gatt_db_attribute *attrib, void *user_data)
Definition at line 107 of file gatt-db.h.
typedef void(* gatt_db_attribute_read_t)(struct gatt_db_attribute *attrib, int err, const uint8_t *value, size_t length, void *user_data)
Definition at line 212 of file gatt-db.h.
typedef void(* gatt_db_attribute_write_t)(struct gatt_db_attribute *attrib, int err, void *user_data)
Definition at line 224 of file gatt-db.h.
typedef void(* gatt_db_destroy_func_t)(void *user_data)
Definition at line 164 of file gatt-db.h.
typedef void(* gatt_db_read_t)(struct gatt_db_attribute *attrib, unsigned int id, uint16_t offset, uint8_t opcode, struct bt_att *att, void *user_data)
Definition at line 51 of file gatt-db.h.
typedef void(* gatt_db_write_t)(struct gatt_db_attribute *attrib, unsigned int id, uint16_t offset, const uint8_t *value, size_t len, uint8_t opcode, struct bt_att *att, void *user_data)
Definition at line 56 of file gatt-db.h.
Function Documentation
struct gatt_db_attribute* gatt_db_add_service (struct gatt_db * db, const bt_uuid_t * uuid, bool primary, uint16_t num_handles)
Definition at line 596 of file gatt-db.c.
References gatt_db_insert_service(), and gatt_db::next_handle.
bool gatt_db_attribute_get_char_data (const struct gatt_db_attribute * attrib, uint16_t * handle, uint16_t * value_handle, uint8_t * properties, bt_uuid_t * uuid)
Definition at line 1495 of file gatt-db.c.
References bt_uuid_cmp(), get_le16(), gatt_db_attribute::handle, le_to_uuid(), gatt_db_attribute::uuid, gatt_db_attribute::value, and gatt_db_attribute::value_len.
Referenced by notify_chrc_create(), and print_chrc().
uint16_t gatt_db_attribute_get_handle (const struct gatt_db_attribute * attrib)
Definition at line 1409 of file gatt-db.c.
References gatt_db_attribute::handle.
Referenced by discover_descs(), discover_descs_cb(), discover_incl_cb(), notify_chrc_create(), print_desc(), and register_service_changed().
bool gatt_db_attribute_get_incl_data (const struct gatt_db_attribute * attrib, uint16_t * handle, uint16_t * start_handle, uint16_t * end_handle)
Definition at line 1532 of file gatt-db.c.
References bt_uuid_cmp(), get_le16(), gatt_db_attribute::handle, gatt_db_attribute::uuid, gatt_db_attribute::value, and gatt_db_attribute::value_len.
Referenced by print_incl().
uint32_t gatt_db_attribute_get_permissions (const struct gatt_db_attribute * attrib)
Definition at line 1569 of file gatt-db.c.
References gatt_db_attribute::permissions.
bool gatt_db_attribute_get_service_data (const struct gatt_db_attribute * attrib, uint16_t * start_handle, uint16_t * end_handle, bool * primary, bt_uuid_t * uuid)
Definition at line 1465 of file gatt-db.c.
References gatt_db_service::attributes, bt_uuid_cmp(), gatt_db_service_get_handles(), le_to_uuid(), gatt_db_attribute::service, gatt_db_attribute::uuid, gatt_db_attribute::value, and gatt_db_attribute::value_len.
Referenced by print_service().
bool gatt_db_attribute_get_service_handles (const struct gatt_db_attribute * attrib, uint16_t * start_handle, uint16_t * end_handle)
Definition at line 1448 of file gatt-db.c.
References gatt_db_service_get_handles(), and gatt_db_attribute::service.
Referenced by discover_chrcs_cb(), discover_descs_cb(), discover_incl_cb(), discover_secondary_cb(), and log_service_event().
bool gatt_db_attribute_get_service_uuid (const struct gatt_db_attribute * attrib, bt_uuid_t * uuid)
Definition at line 1417 of file gatt-db.c.
References gatt_db_service::attributes, bswap_128(), bt_uuid128_create(), bt_uuid16_create(), get_le16(), gatt_db_attribute::service, gatt_db_attribute::value, and gatt_db_attribute::value_len.
Referenced by find_service_with_uuid(), foreach_service_in_range(), gatt_db_insert_service(), log_service_event(), and print_incl().
const bt_uuid_t* gatt_db_attribute_get_type (const struct gatt_db_attribute * attrib)
Definition at line 1400 of file gatt-db.c.
References gatt_db_attribute::uuid.
Referenced by find_ccc(), notify_chrc_create(), and print_desc().
bool gatt_db_attribute_read (struct gatt_db_attribute * attrib, uint16_t offset, uint8_t opcode, struct bt_att * att, gatt_db_attribute_read_t func, void * user_data)
Definition at line 1590 of file gatt-db.c.
References pending_read::attrib, ATTRIBUTE_TIMEOUT, BT_ATT_ERROR_INVALID_OFFSET, pending_read::func, func, pending_read::id, new0, gatt_db_attribute::pending_reads, queue_push_tail(), gatt_db_attribute::read_func, gatt_db_attribute::read_id, read_timeout(), timeout_add(), pending_read::timeout_id, pending_read::user_data, gatt_db_attribute::user_data, gatt_db_attribute::value, and gatt_db_attribute::value_len.
bool gatt_db_attribute_read_result (struct gatt_db_attribute * attrib, unsigned int id, int err, const uint8_t * value, size_t length)
Definition at line 1642 of file gatt-db.c.
References find_pending(), pending_read_result(), gatt_db_attribute::pending_reads, queue_remove_if(), and UINT_TO_PTR.
bool gatt_db_attribute_reset (struct gatt_db_attribute * attrib)
Definition at line 1752 of file gatt-db.c.
References gatt_db_attribute::value, and gatt_db_attribute::value_len.
bool gatt_db_attribute_write (struct gatt_db_attribute * attrib, uint16_t offset, const uint8_t * value, size_t len, uint8_t opcode, struct bt_att * att, gatt_db_attribute_write_t func, void * user_data)
Definition at line 1674 of file gatt-db.c.
References pending_write::attrib, ATTRIBUTE_TIMEOUT, pending_write::func, func, pending_write::id, new0, gatt_db_attribute::pending_writes, queue_push_tail(), timeout_add(), pending_write::timeout_id, pending_write::user_data, gatt_db_attribute::user_data, gatt_db_attribute::value, gatt_db_attribute::value_len, gatt_db_attribute::write_func, gatt_db_attribute::write_id, and write_timeout().
bool gatt_db_attribute_write_result (struct gatt_db_attribute * attrib, unsigned int id, int err)
Definition at line 1734 of file gatt-db.c.
References find_pending(), pending_write_result(), gatt_db_attribute::pending_writes, queue_remove_if(), and UINT_TO_PTR.
bool gatt_db_clear (struct gatt_db * db)
Definition at line 442 of file gatt-db.c.
References gatt_db_service_destroy(), gatt_db::next_handle, queue_remove_all(), and gatt_db::services.
Referenced by init_fail().
bool gatt_db_clear_range (struct gatt_db * db, uint16_t start_handle, uint16_t end_handle)
Definition at line 481 of file gatt-db.c.
References clear_range::end, gatt_db_service_destroy(), match_range(), queue_remove_all(), gatt_db::services, and clear_range::start.
Referenced by discover_primary_cb(), discover_secondary_cb(), process_service_changed(), service_changed_complete(), and service_changed_failure().
unsigned int gatt_db_find_by_type (struct gatt_db * db, uint16_t start_handle, uint16_t end_handle, const bt_uuid_t * type, gatt_db_attribute_cb_t func, void * user_data)
Definition at line 1056 of file gatt-db.c.
References find_by_type_value_data::end_handle, find_by_type(), find_by_type_value_data::func, func, find_by_type_value_data::num_of_res, queue_foreach(), gatt_db::services, find_by_type_value_data::start_handle, type, find_by_type_value_data::user_data, and find_by_type_value_data::uuid.
Referenced by register_service_changed().
unsigned int gatt_db_find_by_type_value (struct gatt_db * db, uint16_t start_handle, uint16_t end_handle, const bt_uuid_t * type, const void * value, size_t value_len, gatt_db_attribute_cb_t func, void * user_data)
Definition at line 1077 of file gatt-db.c.
References find_by_type_value_data::end_handle, find_by_type(), find_by_type_value_data::func, func, find_by_type_value_data::num_of_res, queue_foreach(), gatt_db::services, find_by_type_value_data::start_handle, type, find_by_type_value_data::user_data, find_by_type_value_data::uuid, find_by_type_value_data::value, and find_by_type_value_data::value_len.
void gatt_db_find_information (struct gatt_db * db, uint16_t start_handle, uint16_t end_handle, struct queue * queue)
Definition at line 1187 of file gatt-db.c.
References find_information_data::end_handle, find_information(), find_information_data::queue, queue_foreach(), gatt_db::services, and find_information_data::start_handle.
void gatt_db_foreach_service (struct gatt_db * db, const bt_uuid_t * uuid, gatt_db_attribute_cb_t func, void * user_data)
Definition at line 1200 of file gatt-db.c.
References gatt_db_foreach_service_in_range().
Referenced by print_services(), print_services_by_handle(), and print_services_by_uuid().
void gatt_db_foreach_service_in_range (struct gatt_db * db, const bt_uuid_t * uuid, gatt_db_attribute_cb_t func, void * user_data, uint16_t start_handle, uint16_t end_handle)
Definition at line 1237 of file gatt-db.c.
References foreach_data::end, foreach_service_in_range(), foreach_data::func, func, queue_foreach(), gatt_db::services, foreach_data::start, foreach_data::user_data, and foreach_data::uuid.
Referenced by gatt_db_foreach_service(), and service_changed_cb().
struct gatt_db_attribute* gatt_db_get_attribute (struct gatt_db * db, uint16_t handle)
Definition at line 1349 of file gatt-db.c.
References gatt_db_service::attributes, find_service_for_handle(), gatt_db_attribute::handle, gatt_db_service::num_handles, queue_find(), gatt_db::services, and UINT_TO_PTR.
Referenced by discover_incl_cb(), notify_chrc_create(), and print_incl().
struct gatt_db_attribute* gatt_db_get_service_with_uuid (struct gatt_db * db, const bt_uuid_t * uuid)
Definition at line 1385 of file gatt-db.c.
References gatt_db_service::attributes, find_service_with_uuid(), queue_find(), and gatt_db::services.
struct gatt_db_attribute* gatt_db_insert_service (struct gatt_db * db, uint16_t handle, const bt_uuid_t * uuid, bool primary, uint16_t num_handles)
Definition at line 531 of file gatt-db.c.
References gatt_db_service::attributes, bt_uuid_cmp(), gatt_db_service::db, find_insert_loc(), gatt_db_attribute_get_service_uuid(), gatt_db_service_create(), gatt_db_service_destroy(), gatt_db_attribute::handle, MAX, gatt_db::next_handle, gatt_db_service::num_handles, primary_service_uuid, queue_push_after(), queue_push_head(), secondary_service_uuid, gatt_db::services, type, and gatt_db_attribute::uuid.
Referenced by discover_primary_cb(), discover_secondary_cb(), and gatt_db_add_service().
bool gatt_db_isempty (struct gatt_db * db)
Definition at line 339 of file gatt-db.c.
References queue_isempty(), and gatt_db::services.
struct gatt_db* gatt_db_new (void)
Definition at line 218 of file gatt-db.c.
References gatt_db_ref(), new0, gatt_db::next_handle, gatt_db::notify_list, queue_destroy(), queue_new(), and gatt_db::services.
Referenced by client_create().
void gatt_db_read_by_group_type (struct gatt_db * db, uint16_t start_handle, uint16_t end_handle, const bt_uuid_t type, struct queue * queue)
Definition at line 968 of file gatt-db.c.
References gatt_db_service::active, gatt_db_service::attributes, bt_uuid_cmp(), queue_entry::data, gatt_db_attribute::handle, queue_entry::next, gatt_db_service::num_handles, queue_get_entries(), queue_push_tail(), gatt_db::services, gatt_db_attribute::uuid, and gatt_db_attribute::value_len.
void gatt_db_read_by_type (struct gatt_db * db, uint16_t start_handle, uint16_t end_handle, const bt_uuid_t type, struct queue * queue)
Definition at line 1136 of file gatt-db.c.
References read_by_type_data::end_handle, read_by_type_data::queue, queue_foreach(), read_by_type(), gatt_db::services, read_by_type_data::start_handle, type, and read_by_type_data::uuid.
struct gatt_db* gatt_db_ref (struct gatt_db * db)
Definition at line 208 of file gatt-db.c.
References gatt_db::ref_count.
Referenced by bt_gatt_client_new(), gatt_db_new(), and notify_service_changed().
unsigned int gatt_db_register (struct gatt_db * db, gatt_db_attribute_cb_t service_added, gatt_db_attribute_cb_t service_removed, void * user_data, gatt_db_destroy_func_t destroy)
Definition at line 605 of file gatt-db.c.
References notify::destroy, notify::id, new0, gatt_db::next_notify_id, gatt_db::notify_list, queue_push_tail(), notify::service_added, notify::service_removed, and notify::user_data.
Referenced by client_create().
bool gatt_db_remove_service (struct gatt_db * db, struct gatt_db_attribute * attrib)
Definition at line 425 of file gatt-db.c.
References gatt_db_service_destroy(), queue_remove(), gatt_db_attribute::service, and gatt_db::services.
struct gatt_db_attribute* gatt_db_service_add_characteristic (struct gatt_db_attribute * attrib, const bt_uuid_t * uuid, uint32_t permissions, uint8_t properties, gatt_db_read_t read_func, gatt_db_write_t write_func, void * user_data)
Definition at line 785 of file gatt-db.c.
References gatt_db_attribute::service, and service_insert_characteristic().
struct gatt_db_attribute* gatt_db_service_add_descriptor (struct gatt_db_attribute * attrib, const bt_uuid_t * uuid, uint32_t permissions, gatt_db_read_t read_func, gatt_db_write_t write_func, void * user_data)
Definition at line 852 of file gatt-db.c.
References gatt_db_attribute::service, and service_insert_descriptor().
struct gatt_db_attribute* gatt_db_service_add_included (struct gatt_db_attribute * attrib, struct gatt_db_attribute * include)
Definition at line 868 of file gatt-db.c.
References attribute_update(), gatt_db_service::attributes, get_attribute_index(), gatt_db_attribute::handle, MAX_INCLUDED_VALUE_LEN, new_attribute(), gatt_db_service::num_handles, put_le16(), gatt_db_attribute::service, set_attribute_data(), gatt_db_attribute::value, and gatt_db_attribute::value_len.
Referenced by discover_incl_cb().
void gatt_db_service_foreach (struct gatt_db_attribute * attrib, const bt_uuid_t * uuid, gatt_db_attribute_cb_t func, void * user_data)
Definition at line 1258 of file gatt-db.c.
References gatt_db_service::attributes, bt_uuid_cmp(), func, gatt_db_service::num_handles, gatt_db_attribute::service, and gatt_db_attribute::uuid.
Referenced by gatt_db_service_foreach_char(), and gatt_db_service_foreach_incl().
void gatt_db_service_foreach_char (struct gatt_db_attribute * attrib, gatt_db_attribute_cb_t func, void * user_data)
Definition at line 1284 of file gatt-db.c.
References gatt_db_service_foreach().
Referenced by print_service().
void gatt_db_service_foreach_desc (struct gatt_db_attribute * attrib, gatt_db_attribute_cb_t func, void * user_data)
Definition at line 1291 of file gatt-db.c.
References gatt_db_service::attributes, bt_uuid_cmp(), func, gatt_db_service::num_handles, gatt_db_attribute::service, and gatt_db_attribute::uuid.
Referenced by notify_chrc_create(), and print_chrc().
void gatt_db_service_foreach_incl (struct gatt_db_attribute * attrib, gatt_db_attribute_cb_t func, void * user_data)
Definition at line 1330 of file gatt-db.c.
References gatt_db_service_foreach().
Referenced by print_service().
bool gatt_db_service_get_active (struct gatt_db_attribute * attrib)
Definition at line 941 of file gatt-db.c.
References gatt_db_service::active, and gatt_db_attribute::service.
Referenced by discover_primary_cb(), and discover_secondary_cb().
bool gatt_db_service_get_claimed (struct gatt_db_attribute * attrib)
Definition at line 960 of file gatt-db.c.
References gatt_db_service::claimed, and gatt_db_attribute::service.
struct gatt_db_attribute* gatt_db_service_insert_characteristic (struct gatt_db_attribute * attrib, uint16_t handle, const bt_uuid_t * uuid, uint32_t permissions, uint8_t properties, gatt_db_read_t read_func, gatt_db_write_t write_func, void * user_data)
Definition at line 766 of file gatt-db.c.
References gatt_db_attribute::service, and service_insert_characteristic().
Referenced by discover_descs().
struct gatt_db_attribute* gatt_db_service_insert_descriptor (struct gatt_db_attribute * attrib, uint16_t handle, const bt_uuid_t * uuid, uint32_t permissions, gatt_db_read_t read_func, gatt_db_write_t write_func, void * user_data)
Definition at line 835 of file gatt-db.c.
References gatt_db_attribute::service, and service_insert_descriptor().
Referenced by discover_descs_cb().
bool gatt_db_service_set_active (struct gatt_db_attribute * attrib, bool active)
Definition at line 922 of file gatt-db.c.
References gatt_db_service::active, gatt_db_service::db, notify_service_changed(), and gatt_db_attribute::service.
Referenced by discover_chrcs_cb(), and discover_descs_cb().
bool gatt_db_service_set_claimed (struct gatt_db_attribute * attrib, bool claimed)
Definition at line 949 of file gatt-db.c.
References gatt_db_service::claimed, and gatt_db_attribute::service.
void gatt_db_unref (struct gatt_db * db)
Definition at line 328 of file gatt-db.c.
References gatt_db_destroy(), and gatt_db::ref_count.
Referenced by bt_gatt_client_free(), client_create(), and notify_service_changed().
bool gatt_db_unregister (struct gatt_db * db, unsigned int id)
Definition at line 638 of file gatt-db.c.
References match_notify_id(), notify_destroy(), gatt_db::notify_list, queue_find(), queue_remove(), and UINT_TO_PTR.