ble_gatt_client: src/io-mainloop.c File Reference
io-mainloop.c File Reference
set of function to manage io part of the mainloop feature
#include <unistd.h>
#include <errno.h>
#include <sys/socket.h>
#include "mainloop.h"
#include "util.h"
#include "io.h"
Data Structures
struct io
Functions
static struct io * io_ref (struct io *io)
static void io_unref (struct io *io)
static void io_cleanup (void *user_data)
static void io_callback (int fd, uint32_t events, void *user_data)
struct io * io_new (int fd)
void io_destroy (struct io *io)
int io_get_fd (struct io *io)
bool io_set_close_on_destroy (struct io *io, bool do_close)
bool io_set_read_handler (struct io *io, io_callback_func_t callback, void *user_data, io_destroy_func_t destroy)
bool io_set_write_handler (struct io *io, io_callback_func_t callback, void *user_data, io_destroy_func_t destroy)
bool io_set_disconnect_handler (struct io *io, io_callback_func_t callback, void *user_data, io_destroy_func_t destroy)
ssize_t io_send (struct io *io, const struct iovec *iov, int iovcnt)
bool io_shutdown (struct io *io)
Detailed Description
set of function to manage io part of the mainloop feature
See also
mainloop.c
Author
Gilbert Brault
Copyright
Gilbert Brault 2015 the original work comes from bluez v5.39 value add: documenting main features
Definition in file io-mainloop.c.
Function Documentation
static void io_callback (int fd, uint32_t events, void * user_data) static
Definition at line 102 of file io-mainloop.c.
References io::disconnect_callback, io::disconnect_data, io::disconnect_destroy, io::events, io::fd, io_ref(), io_unref(), mainloop_modify_fd(), mainloop_remove_fd(), io::read_callback, io::read_data, io::read_destroy, io::write_callback, io::write_data, and io::write_destroy.
Referenced by io_new().
static void io_cleanup (void * user_data) static
Definition at line 83 of file io-mainloop.c.
References io::close_on_destroy, io::disconnect_data, io::disconnect_destroy, io::fd, io::read_data, io::read_destroy, io::write_data, and io::write_destroy.
Referenced by io_new().
void io_destroy (struct io * io)
Definition at line 189 of file io-mainloop.c.
References io::disconnect_callback, io::fd, io_unref(), mainloop_remove_fd(), io::read_callback, and io::write_callback.
Referenced by bt_att_free(), and disconnect_cb().
int io_get_fd (struct io * io)
Definition at line 203 of file io-mainloop.c.
References io::fd.
struct io* io_new (int fd)
Definition at line 165 of file io-mainloop.c.
References io::close_on_destroy, io::events, io::fd, io_callback(), io_cleanup(), io_ref(), mainloop_add_fd(), and new0.
Referenced by bt_att_new().
static struct io* io_ref (struct io * io) static
Definition at line 62 of file io-mainloop.c.
References io::ref_count.
Referenced by io_callback(), and io_new().
ssize_t io_send (struct io * io, const struct iovec * iov, int iovcnt)
send data to the underlying socket (actual write)
Parameters
io io structure which describe the underlying socket and its context
iov pointer to pdu, pdu length structure
iovcnt number of pdu to send (iov is an array)
Returns
The return value is a count of bytes written, or -errno indicating an error.
Definition at line 322 of file io-mainloop.c.
References io::fd.
Referenced by can_write_data().
bool io_set_close_on_destroy (struct io * io, bool do_close)
Definition at line 211 of file io-mainloop.c.
References io::close_on_destroy.
Referenced by bt_att_set_close_on_unref().
bool io_set_disconnect_handler (struct io * io, io_callback_func_t callback, void * user_data, io_destroy_func_t destroy)
Definition at line 283 of file io-mainloop.c.
References io::disconnect_callback, io::disconnect_data, io::disconnect_destroy, io::events, io::fd, and mainloop_modify_fd().
Referenced by bt_att_new().
bool io_set_read_handler (struct io * io, io_callback_func_t callback, void * user_data, io_destroy_func_t destroy)
Definition at line 221 of file io-mainloop.c.
References io::events, io::fd, mainloop_modify_fd(), io::read_callback, io::read_data, and io::read_destroy.
Referenced by bt_att_new().
bool io_set_write_handler (struct io * io, io_callback_func_t callback, void * user_data, io_destroy_func_t destroy)
Definition at line 252 of file io-mainloop.c.
References io::events, io::fd, mainloop_modify_fd(), io::write_callback, io::write_data, and io::write_destroy.
Referenced by wakeup_writer().
bool io_shutdown (struct io * io)
Definition at line 339 of file io-mainloop.c.
References io::fd.
Referenced by can_read_data(), handle_conf(), handle_rsp(), and timeout_cb().
static void io_unref (struct io * io) static
Definition at line 72 of file io-mainloop.c.
References io::ref_count.
Referenced by io_callback(), and io_destroy().