ble_gatt_client: src/queue.c File Reference
queue.c File Reference
set of function to manage queues
#include "util.h"
#include "queue.h"
Data Structures
struct queue
Functions
static struct queue * queue_ref (struct queue *queue)
static void queue_unref (struct queue *queue)
struct queue * queue_new (void)
void queue_destroy (struct queue *queue, queue_destroy_func_t destroy)
static struct queue_entry * queue_entry_ref (struct queue_entry *entry)
static void queue_entry_unref (struct queue_entry *entry)
static struct queue_entry * queue_entry_new (void *data)
bool queue_push_tail (struct queue *queue, void *data)
bool queue_push_head (struct queue *queue, void *data)
bool queue_push_after (struct queue *queue, void *entry, void *data)
void * queue_pop_head (struct queue *queue)
void * queue_peek_head (struct queue *queue)
void * queue_peek_tail (struct queue *queue)
void queue_foreach (struct queue *queue, queue_foreach_func_t function, void *user_data)
static bool direct_match (const void *a, const void *b)
void * queue_find (struct queue *queue, queue_match_func_t function, const void *match_data)
bool queue_remove (struct queue *queue, void *data)
void * queue_remove_if (struct queue *queue, queue_match_func_t function, void *user_data)
unsigned int queue_remove_all (struct queue *queue, queue_match_func_t function, void *user_data, queue_destroy_func_t destroy)
const struct queue_entry * queue_get_entries (struct queue *queue)
unsigned int queue_length (struct queue *queue)
bool queue_isempty (struct queue *queue)
Detailed Description
set of function to manage queues
Author
Gilbert Brault
Copyright
Gilbert Brault 2015 the original work comes from bluez v5.39 value add: documenting main features
Definition in file queue.c.
Function Documentation
static bool direct_match (const void * a, const void * b) static
Definition at line 271 of file queue.c.
Referenced by queue_find().
void queue_destroy (struct queue * queue, queue_destroy_func_t destroy)
Definition at line 80 of file queue.c.
References queue_remove_all(), and queue_unref().
Referenced by attribute_destroy(), bt_att_free(), bt_gatt_client_free(), discovery_op_free(), gatt_db_destroy(), gatt_db_new(), and notify_chrc_free().
static struct queue_entry* queue_entry_new (void * data) static
Definition at line 108 of file queue.c.
References queue_entry::data, new0, and queue_entry_ref().
Referenced by queue_push_after(), queue_push_head(), and queue_push_tail().
static struct queue_entry* queue_entry_ref (struct queue_entry * entry) static
Definition at line 90 of file queue.c.
References queue_entry::ref_count.
Referenced by queue_entry_new(), and queue_foreach().
static void queue_entry_unref (struct queue_entry * entry) static
Definition at line 100 of file queue.c.
References queue_entry::ref_count.
Referenced by queue_foreach(), queue_pop_head(), queue_remove(), queue_remove_all(), and queue_remove_if().
void* queue_find (struct queue * queue, queue_match_func_t function, const void * match_data)
Definition at line 276 of file queue.c.
References queue_entry::data, direct_match(), queue::head, and queue_entry::next.
Referenced by bt_gatt_client_write_execute(), gatt_db_get_attribute(), gatt_db_get_service_with_uuid(), gatt_db_unregister(), get_reliable_request(), and register_notify().
void queue_foreach (struct queue * queue, queue_foreach_func_t function, void * user_data)
Definition at line 242 of file queue.c.
References queue_entry::data, queue::head, queue_entry::next, queue_entry_ref(), queue_entry_unref(), queue_ref(), queue_unref(), and queue::ref_count.
Referenced by disconnect_cb(), gatt_db_find_by_type(), gatt_db_find_by_type_value(), gatt_db_find_information(), gatt_db_foreach_service_in_range(), gatt_db_read_by_type(), notify_cb(), and notify_service_changed().
const struct queue_entry* queue_get_entries (struct queue * queue)
Definition at line 406 of file queue.c.
References queue::head.
Referenced by find_insert_loc(), gatt_db_read_by_group_type(), and handle_notify().
bool queue_isempty (struct queue * queue)
Definition at line 422 of file queue.c.
References queue::entries.
Referenced by cancel_long_write_cb(), discover_primary_cb(), gatt_db_isempty(), handle_notify(), notify_service_changed(), start_next_long_write(), and wakeup_writer().
unsigned int queue_length (struct queue * queue)
Definition at line 414 of file queue.c.
References queue::entries.
struct queue* queue_new (void)
Definition at line 65 of file queue.c.
References queue::entries, queue::head, new0, queue_ref(), and queue::tail.
Referenced by bt_att_new(), bt_gatt_client_new(), discovery_op_create(), gatt_db_new(), new_attribute(), and notify_chrc_create().
void* queue_peek_head (struct queue * queue)
Definition at line 226 of file queue.c.
References queue_entry::data, and queue::head.
void* queue_peek_tail (struct queue * queue)
Definition at line 234 of file queue.c.
References queue_entry::data, and queue::tail.
void* queue_pop_head (struct queue * queue)
Definition at line 202 of file queue.c.
References queue_entry::data, queue::entries, queue::head, queue_entry::next, queue_entry_unref(), and queue::tail.
Referenced by disable_ccc_callback(), discover_chrcs_cb(), discover_descs(), discover_descs_cb(), discover_incl_cb(), discover_secondary_cb(), enable_ccc_callback(), pick_next_send_op(), service_changed_complete(), and start_next_long_write().
bool queue_push_after (struct queue * queue, void * entry, void * data)
Definition at line 168 of file queue.c.
References queue_entry::data, queue::entries, queue::head, queue_entry::next, queue_entry_new(), and queue::tail.
Referenced by gatt_db_insert_service().
bool queue_push_head (struct queue * queue, void * data)
Definition at line 145 of file queue.c.
References queue::entries, queue::head, queue_entry::next, queue_entry_new(), and queue::tail.
Referenced by gatt_db_insert_service(), and handle_error_rsp().
bool queue_push_tail (struct queue * queue, void * data)
Definition at line 121 of file queue.c.
References queue::entries, queue::head, queue_entry::next, queue_entry_new(), and queue::tail.
Referenced by bt_att_register(), bt_att_register_disconnect(), bt_att_send(), bt_gatt_client_write_long_value(), discover_chrcs_cb(), discover_incl_cb(), discover_primary_cb(), discover_secondary_cb(), find_information(), gatt_db_attribute_read(), gatt_db_attribute_write(), gatt_db_read_by_group_type(), gatt_db_register(), notify_chrc_create(), read_by_type(), register_notify(), request_create(), and service_changed_cb().
static struct queue* queue_ref (struct queue * queue) static
Definition at line 47 of file queue.c.
References queue::ref_count.
Referenced by queue_foreach(), and queue_new().
bool queue_remove (struct queue * queue, void * data)
Definition at line 294 of file queue.c.
References queue_entry::data, queue::entries, queue::head, queue_entry::next, queue_entry_unref(), and queue::tail.
Referenced by cancel_long_write_req(), enable_ccc_callback(), gatt_db_remove_service(), gatt_db_unregister(), read_timeout(), register_notify(), request_unref(), and write_timeout().
unsigned int queue_remove_all (struct queue * queue, queue_match_func_t function, void * user_data, queue_destroy_func_t destroy)
Definition at line 360 of file queue.c.
References queue_entry::data, queue::entries, queue::head, queue_entry::next, queue_entry_unref(), queue_remove_if(), and queue::tail.
Referenced by bt_att_cancel_all(), bt_att_unregister_all(), bt_gatt_client_cancel_all(), enable_ccc_callback(), gatt_client_remove_all_notify_in_range(), gatt_client_remove_notify_chrcs_in_range(), gatt_db_clear(), gatt_db_clear_range(), and queue_destroy().
void* queue_remove_if (struct queue * queue, queue_match_func_t function, void * user_data)
Definition at line 323 of file queue.c.
References queue_entry::data, queue::entries, queue::head, queue_entry::next, queue_entry_unref(), and queue::tail.
Referenced by bt_att_cancel(), bt_att_unregister(), bt_att_unregister_disconnect(), bt_gatt_client_cancel(), bt_gatt_client_unregister_notify(), gatt_db_attribute_read_result(), gatt_db_attribute_write_result(), and queue_remove_all().
static void queue_unref (struct queue * queue) static
Definition at line 57 of file queue.c.
References queue::ref_count.
Referenced by queue_destroy(), and queue_foreach().