ble_gatt_client: src/timeout.h File Reference
timeout.h File Reference
#include <stdbool.h>
Typedefs
typedef bool(* timeout_func_t)(void *user_data)
typedef void(* timeout_destroy_func_t)(void *user_data)
Functions
unsigned int timeout_add (unsigned int timeout, timeout_func_t func, void *user_data, timeout_destroy_func_t destroy)
void timeout_remove (unsigned int id)
Typedef Documentation
typedef void(* timeout_destroy_func_t)(void *user_data)
Definition at line 23 of file timeout.h.
typedef bool(* timeout_func_t)(void *user_data)
Definition at line 22 of file timeout.h.
Function Documentation
unsigned int timeout_add (unsigned int timeout, timeout_func_t func, void * user_data, timeout_destroy_func_t destroy)
Definition at line 58 of file timeout-glib.c.
References timeout_data::destroy, timeout_data::func, func, timeout_data::id, timeout_callback(), timeout_destroy(), and timeout_data::user_data.
Referenced by can_write_data(), gatt_db_attribute_read(), and gatt_db_attribute_write().
void timeout_remove (unsigned int id)
Definition at line 80 of file timeout-glib.c.
Referenced by destroy_att_send_op(), pending_read_result(), and pending_write_result().