ble_gatt_client: src/uuid.h File Reference
uuid.h File Reference
#include <stdint.h>
Data Structures
struct bt_uuid_t
Macros
#define GENERIC_AUDIO_UUID "00001203-0000-1000-8000-00805f9b34fb"
#define HSP_HS_UUID "00001108-0000-1000-8000-00805f9b34fb"
#define HSP_AG_UUID "00001112-0000-1000-8000-00805f9b34fb"
#define HFP_HS_UUID "0000111e-0000-1000-8000-00805f9b34fb"
#define HFP_AG_UUID "0000111f-0000-1000-8000-00805f9b34fb"
#define ADVANCED_AUDIO_UUID "0000110d-0000-1000-8000-00805f9b34fb"
#define A2DP_SOURCE_UUID "0000110a-0000-1000-8000-00805f9b34fb"
#define A2DP_SINK_UUID "0000110b-0000-1000-8000-00805f9b34fb"
#define AVRCP_REMOTE_UUID "0000110e-0000-1000-8000-00805f9b34fb"
#define AVRCP_TARGET_UUID "0000110c-0000-1000-8000-00805f9b34fb"
#define PANU_UUID "00001115-0000-1000-8000-00805f9b34fb"
#define NAP_UUID "00001116-0000-1000-8000-00805f9b34fb"
#define GN_UUID "00001117-0000-1000-8000-00805f9b34fb"
#define BNEP_SVC_UUID "0000000f-0000-1000-8000-00805f9b34fb"
#define PNPID_UUID "00002a50-0000-1000-8000-00805f9b34fb"
#define DEVICE_INFORMATION_UUID "0000180a-0000-1000-8000-00805f9b34fb"
#define GATT_UUID "00001801-0000-1000-8000-00805f9b34fb"
#define IMMEDIATE_ALERT_UUID "00001802-0000-1000-8000-00805f9b34fb"
#define LINK_LOSS_UUID "00001803-0000-1000-8000-00805f9b34fb"
#define TX_POWER_UUID "00001804-0000-1000-8000-00805f9b34fb"
#define BATTERY_UUID "0000180f-0000-1000-8000-00805f9b34fb"
#define SCAN_PARAMETERS_UUID "00001813-0000-1000-8000-00805f9b34fb"
#define SAP_UUID "0000112D-0000-1000-8000-00805f9b34fb"
#define HEART_RATE_UUID "0000180d-0000-1000-8000-00805f9b34fb"
#define HEART_RATE_MEASUREMENT_UUID "00002a37-0000-1000-8000-00805f9b34fb"
#define BODY_SENSOR_LOCATION_UUID "00002a38-0000-1000-8000-00805f9b34fb"
#define HEART_RATE_CONTROL_POINT_UUID "00002a39-0000-1000-8000-00805f9b34fb"
#define HEALTH_THERMOMETER_UUID "00001809-0000-1000-8000-00805f9b34fb"
#define TEMPERATURE_MEASUREMENT_UUID "00002a1c-0000-1000-8000-00805f9b34fb"
#define TEMPERATURE_TYPE_UUID "00002a1d-0000-1000-8000-00805f9b34fb"
#define INTERMEDIATE_TEMPERATURE_UUID "00002a1e-0000-1000-8000-00805f9b34fb"
#define MEASUREMENT_INTERVAL_UUID "00002a21-0000-1000-8000-00805f9b34fb"
#define CYCLING_SC_UUID "00001816-0000-1000-8000-00805f9b34fb"
#define CSC_MEASUREMENT_UUID "00002a5b-0000-1000-8000-00805f9b34fb"
#define CSC_FEATURE_UUID "00002a5c-0000-1000-8000-00805f9b34fb"
#define SENSOR_LOCATION_UUID "00002a5d-0000-1000-8000-00805f9b34fb"
#define SC_CONTROL_POINT_UUID "00002a55-0000-1000-8000-00805f9b34fb"
#define RFCOMM_UUID_STR "00000003-0000-1000-8000-00805f9b34fb"
#define HDP_UUID "00001400-0000-1000-8000-00805f9b34fb"
#define HDP_SOURCE_UUID "00001401-0000-1000-8000-00805f9b34fb"
#define HDP_SINK_UUID "00001402-0000-1000-8000-00805f9b34fb"
#define HID_UUID "00001124-0000-1000-8000-00805f9b34fb"
#define DUN_GW_UUID "00001103-0000-1000-8000-00805f9b34fb"
#define GAP_UUID "00001800-0000-1000-8000-00805f9b34fb"
#define PNP_UUID "00001200-0000-1000-8000-00805f9b34fb"
#define SPP_UUID "00001101-0000-1000-8000-00805f9b34fb"
#define OBEX_SYNC_UUID "00001104-0000-1000-8000-00805f9b34fb"
#define OBEX_OPP_UUID "00001105-0000-1000-8000-00805f9b34fb"
#define OBEX_FTP_UUID "00001106-0000-1000-8000-00805f9b34fb"
#define OBEX_PCE_UUID "0000112e-0000-1000-8000-00805f9b34fb"
#define OBEX_PSE_UUID "0000112f-0000-1000-8000-00805f9b34fb"
#define OBEX_PBAP_UUID "00001130-0000-1000-8000-00805f9b34fb"
#define OBEX_MAS_UUID "00001132-0000-1000-8000-00805f9b34fb"
#define OBEX_MNS_UUID "00001133-0000-1000-8000-00805f9b34fb"
#define OBEX_MAP_UUID "00001134-0000-1000-8000-00805f9b34fb"
#define GATT_PRIM_SVC_UUID 0x2800
#define GATT_SND_SVC_UUID 0x2801
#define GATT_INCLUDE_UUID 0x2802
#define GATT_CHARAC_UUID 0x2803
#define GATT_CHARAC_DEVICE_NAME 0x2A00
#define GATT_CHARAC_APPEARANCE 0x2A01
#define GATT_CHARAC_PERIPHERAL_PRIV_FLAG 0x2A02
#define GATT_CHARAC_RECONNECTION_ADDRESS 0x2A03
#define GATT_CHARAC_PERIPHERAL_PREF_CONN 0x2A04
#define GATT_CHARAC_SERVICE_CHANGED 0x2A05
#define GATT_CHARAC_SYSTEM_ID 0x2A23
#define GATT_CHARAC_MODEL_NUMBER_STRING 0x2A24
#define GATT_CHARAC_SERIAL_NUMBER_STRING 0x2A25
#define GATT_CHARAC_FIRMWARE_REVISION_STRING 0x2A26
#define GATT_CHARAC_HARDWARE_REVISION_STRING 0x2A27
#define GATT_CHARAC_SOFTWARE_REVISION_STRING 0x2A28
#define GATT_CHARAC_MANUFACTURER_NAME_STRING 0x2A29
#define GATT_CHARAC_PNP_ID 0x2A50
#define GATT_CHARAC_EXT_PROPER_UUID 0x2900
#define GATT_CHARAC_USER_DESC_UUID 0x2901
#define GATT_CLIENT_CHARAC_CFG_UUID 0x2902
#define GATT_SERVER_CHARAC_CFG_UUID 0x2903
#define GATT_CHARAC_FMT_UUID 0x2904
#define GATT_CHARAC_AGREG_FMT_UUID 0x2905
#define GATT_CHARAC_VALID_RANGE_UUID 0x2906
#define GATT_EXTERNAL_REPORT_REFERENCE 0x2907
#define GATT_REPORT_REFERENCE 0x2908
#define MAX_LEN_UUID_STR 37
Functions
int bt_uuid_strcmp (const void *a, const void *b)
int bt_uuid16_create (bt_uuid_t *btuuid, uint16_t value)
int bt_uuid32_create (bt_uuid_t *btuuid, uint32_t value)
int bt_uuid128_create (bt_uuid_t *btuuid, uint128_t value)
int bt_uuid_cmp (const bt_uuid_t *uuid1, const bt_uuid_t *uuid2)
void bt_uuid_to_uuid128 (const bt_uuid_t *src, bt_uuid_t *dst)
int bt_uuid_to_string (const bt_uuid_t *uuid, char *str, size_t n)
int bt_string_to_uuid (bt_uuid_t *uuid, const char *string)
int bt_uuid_to_le (const bt_uuid_t *uuid, void *dst)
static int bt_uuid_len (const bt_uuid_t *uuid)
Macro Definition Documentation
#define A2DP_SINK_UUID "0000110b-0000-1000-8000-00805f9b34fb"
Definition at line 45 of file uuid.h.
#define A2DP_SOURCE_UUID "0000110a-0000-1000-8000-00805f9b34fb"
Definition at line 44 of file uuid.h.
#define ADVANCED_AUDIO_UUID "0000110d-0000-1000-8000-00805f9b34fb"
Definition at line 42 of file uuid.h.
#define AVRCP_REMOTE_UUID "0000110e-0000-1000-8000-00805f9b34fb"
Definition at line 47 of file uuid.h.
#define AVRCP_TARGET_UUID "0000110c-0000-1000-8000-00805f9b34fb"
Definition at line 48 of file uuid.h.
#define BATTERY_UUID "0000180f-0000-1000-8000-00805f9b34fb"
Definition at line 62 of file uuid.h.
#define BNEP_SVC_UUID "0000000f-0000-1000-8000-00805f9b34fb"
Definition at line 53 of file uuid.h.
#define BODY_SENSOR_LOCATION_UUID "00002a38-0000-1000-8000-00805f9b34fb"
Definition at line 69 of file uuid.h.
#define CSC_FEATURE_UUID "00002a5c-0000-1000-8000-00805f9b34fb"
Definition at line 80 of file uuid.h.
#define CSC_MEASUREMENT_UUID "00002a5b-0000-1000-8000-00805f9b34fb"
Definition at line 79 of file uuid.h.
#define CYCLING_SC_UUID "00001816-0000-1000-8000-00805f9b34fb"
Definition at line 78 of file uuid.h.
#define DEVICE_INFORMATION_UUID "0000180a-0000-1000-8000-00805f9b34fb"
Definition at line 56 of file uuid.h.
#define DUN_GW_UUID "00001103-0000-1000-8000-00805f9b34fb"
Definition at line 92 of file uuid.h.
#define GAP_UUID "00001800-0000-1000-8000-00805f9b34fb"
Definition at line 94 of file uuid.h.
#define GATT_CHARAC_AGREG_FMT_UUID 0x2905
Definition at line 137 of file uuid.h.
#define GATT_CHARAC_APPEARANCE 0x2A01
Definition at line 117 of file uuid.h.
#define GATT_CHARAC_DEVICE_NAME 0x2A00
Definition at line 116 of file uuid.h.
#define GATT_CHARAC_EXT_PROPER_UUID 0x2900
Definition at line 132 of file uuid.h.
#define GATT_CHARAC_FIRMWARE_REVISION_STRING 0x2A26
Definition at line 125 of file uuid.h.
#define GATT_CHARAC_FMT_UUID 0x2904
Definition at line 136 of file uuid.h.
#define GATT_CHARAC_HARDWARE_REVISION_STRING 0x2A27
Definition at line 126 of file uuid.h.
#define GATT_CHARAC_MANUFACTURER_NAME_STRING 0x2A29
Definition at line 128 of file uuid.h.
#define GATT_CHARAC_MODEL_NUMBER_STRING 0x2A24
Definition at line 123 of file uuid.h.
#define GATT_CHARAC_PERIPHERAL_PREF_CONN 0x2A04
Definition at line 120 of file uuid.h.
#define GATT_CHARAC_PERIPHERAL_PRIV_FLAG 0x2A02
Definition at line 118 of file uuid.h.
#define GATT_CHARAC_PNP_ID 0x2A50
Definition at line 129 of file uuid.h.
#define GATT_CHARAC_RECONNECTION_ADDRESS 0x2A03
Definition at line 119 of file uuid.h.
#define GATT_CHARAC_SERIAL_NUMBER_STRING 0x2A25
Definition at line 124 of file uuid.h.
#define GATT_CHARAC_SERVICE_CHANGED 0x2A05
Definition at line 121 of file uuid.h.
#define GATT_CHARAC_SOFTWARE_REVISION_STRING 0x2A28
Definition at line 127 of file uuid.h.
#define GATT_CHARAC_SYSTEM_ID 0x2A23
Definition at line 122 of file uuid.h.
#define GATT_CHARAC_USER_DESC_UUID 0x2901
Definition at line 133 of file uuid.h.
#define GATT_CHARAC_UUID 0x2803
Definition at line 113 of file uuid.h.
Referenced by bt_gatt_discover_characteristics(), discover_chrcs_cb(), and notify_chrc_create().
#define GATT_CHARAC_VALID_RANGE_UUID 0x2906
Definition at line 138 of file uuid.h.
#define GATT_CLIENT_CHARAC_CFG_UUID 0x2902
Definition at line 134 of file uuid.h.
Referenced by find_ccc().
#define GATT_EXTERNAL_REPORT_REFERENCE 0x2907
Definition at line 139 of file uuid.h.
#define GATT_INCLUDE_UUID 0x2802
Definition at line 112 of file uuid.h.
Referenced by bt_gatt_discover_included_services(), discover_included_cb(), and read_included_cb().
#define GATT_PRIM_SVC_UUID 0x2800
Definition at line 110 of file uuid.h.
Referenced by discover_services().
#define GATT_REPORT_REFERENCE 0x2908
Definition at line 140 of file uuid.h.
#define GATT_SERVER_CHARAC_CFG_UUID 0x2903
Definition at line 135 of file uuid.h.
#define GATT_SND_SVC_UUID 0x2801
Definition at line 111 of file uuid.h.
Referenced by discover_services().
#define GATT_UUID "00001801-0000-1000-8000-00805f9b34fb"
Definition at line 58 of file uuid.h.
#define GENERIC_AUDIO_UUID "00001203-0000-1000-8000-00805f9b34fb"
Definition at line 34 of file uuid.h.
#define GN_UUID "00001117-0000-1000-8000-00805f9b34fb"
Definition at line 52 of file uuid.h.
#define HDP_SINK_UUID "00001402-0000-1000-8000-00805f9b34fb"
Definition at line 88 of file uuid.h.
#define HDP_SOURCE_UUID "00001401-0000-1000-8000-00805f9b34fb"
Definition at line 87 of file uuid.h.
#define HDP_UUID "00001400-0000-1000-8000-00805f9b34fb"
Definition at line 86 of file uuid.h.
#define HEALTH_THERMOMETER_UUID "00001809-0000-1000-8000-00805f9b34fb"
Definition at line 72 of file uuid.h.
#define HEART_RATE_CONTROL_POINT_UUID "00002a39-0000-1000-8000-00805f9b34fb"
Definition at line 70 of file uuid.h.
#define HEART_RATE_MEASUREMENT_UUID "00002a37-0000-1000-8000-00805f9b34fb"
Definition at line 68 of file uuid.h.
#define HEART_RATE_UUID "0000180d-0000-1000-8000-00805f9b34fb"
Definition at line 67 of file uuid.h.
#define HFP_AG_UUID "0000111f-0000-1000-8000-00805f9b34fb"
Definition at line 40 of file uuid.h.
#define HFP_HS_UUID "0000111e-0000-1000-8000-00805f9b34fb"
Definition at line 39 of file uuid.h.
#define HID_UUID "00001124-0000-1000-8000-00805f9b34fb"
Definition at line 90 of file uuid.h.
#define HSP_AG_UUID "00001112-0000-1000-8000-00805f9b34fb"
Definition at line 37 of file uuid.h.
#define HSP_HS_UUID "00001108-0000-1000-8000-00805f9b34fb"
Definition at line 36 of file uuid.h.
#define IMMEDIATE_ALERT_UUID "00001802-0000-1000-8000-00805f9b34fb"
Definition at line 59 of file uuid.h.
#define INTERMEDIATE_TEMPERATURE_UUID "00002a1e-0000-1000-8000-00805f9b34fb"
Definition at line 75 of file uuid.h.
#define LINK_LOSS_UUID "00001803-0000-1000-8000-00805f9b34fb"
Definition at line 60 of file uuid.h.
#define MAX_LEN_UUID_STR 37
Definition at line 165 of file uuid.h.
Referenced by discover_chrcs_cb(), discover_descs_cb(), discover_incl_cb(), discover_primary_cb(), discover_secondary_cb(), log_service_event(), and print_uuid().
#define MEASUREMENT_INTERVAL_UUID "00002a21-0000-1000-8000-00805f9b34fb"
Definition at line 76 of file uuid.h.
#define NAP_UUID "00001116-0000-1000-8000-00805f9b34fb"
Definition at line 51 of file uuid.h.
#define OBEX_FTP_UUID "00001106-0000-1000-8000-00805f9b34fb"
Definition at line 101 of file uuid.h.
#define OBEX_MAP_UUID "00001134-0000-1000-8000-00805f9b34fb"
Definition at line 107 of file uuid.h.
#define OBEX_MAS_UUID "00001132-0000-1000-8000-00805f9b34fb"
Definition at line 105 of file uuid.h.
#define OBEX_MNS_UUID "00001133-0000-1000-8000-00805f9b34fb"
Definition at line 106 of file uuid.h.
#define OBEX_OPP_UUID "00001105-0000-1000-8000-00805f9b34fb"
Definition at line 100 of file uuid.h.
#define OBEX_PBAP_UUID "00001130-0000-1000-8000-00805f9b34fb"
Definition at line 104 of file uuid.h.
#define OBEX_PCE_UUID "0000112e-0000-1000-8000-00805f9b34fb"
Definition at line 102 of file uuid.h.
#define OBEX_PSE_UUID "0000112f-0000-1000-8000-00805f9b34fb"
Definition at line 103 of file uuid.h.
#define OBEX_SYNC_UUID "00001104-0000-1000-8000-00805f9b34fb"
Definition at line 99 of file uuid.h.
#define PANU_UUID "00001115-0000-1000-8000-00805f9b34fb"
Definition at line 50 of file uuid.h.
#define PNP_UUID "00001200-0000-1000-8000-00805f9b34fb"
Definition at line 95 of file uuid.h.
#define PNPID_UUID "00002a50-0000-1000-8000-00805f9b34fb"
Definition at line 55 of file uuid.h.
#define RFCOMM_UUID_STR "00000003-0000-1000-8000-00805f9b34fb"
Definition at line 84 of file uuid.h.
#define SAP_UUID "0000112D-0000-1000-8000-00805f9b34fb"
Definition at line 65 of file uuid.h.
#define SC_CONTROL_POINT_UUID "00002a55-0000-1000-8000-00805f9b34fb"
Definition at line 82 of file uuid.h.
#define SCAN_PARAMETERS_UUID "00001813-0000-1000-8000-00805f9b34fb"
Definition at line 63 of file uuid.h.
#define SENSOR_LOCATION_UUID "00002a5d-0000-1000-8000-00805f9b34fb"
Definition at line 81 of file uuid.h.
#define SPP_UUID "00001101-0000-1000-8000-00805f9b34fb"
Definition at line 97 of file uuid.h.
#define TEMPERATURE_MEASUREMENT_UUID "00002a1c-0000-1000-8000-00805f9b34fb"
Definition at line 73 of file uuid.h.
#define TEMPERATURE_TYPE_UUID "00002a1d-0000-1000-8000-00805f9b34fb"
Definition at line 74 of file uuid.h.
#define TX_POWER_UUID "00001804-0000-1000-8000-00805f9b34fb"
Definition at line 61 of file uuid.h.
Function Documentation
int bt_string_to_uuid (bt_uuid_t * uuid, const char * string)
Definition at line 285 of file uuid.c.
References bt_string_to_uuid128(), bt_string_to_uuid16(), bt_string_to_uuid32(), is_base_uuid128(), is_uuid128(), is_uuid16(), and is_uuid32().
Referenced by cmd_services().
int bt_uuid128_create (bt_uuid_t * btuuid, uint128_t value)
Definition at line 126 of file uuid.c.
References bt_uuid_t::type, bt_uuid_t::u128, and bt_uuid_t::value.
Referenced by bt_string_to_uuid128(), discover_chrcs_cb(), discover_descs_cb(), discover_incl_cb(), discover_primary_cb(), discover_secondary_cb(), gatt_db_attribute_get_service_uuid(), and le_to_uuid().
int bt_uuid16_create (bt_uuid_t * btuuid, uint16_t value)
Definition at line 108 of file uuid.c.
References bt_uuid_t::type, bt_uuid_t::u16, and bt_uuid_t::value.
Referenced by bt_string_to_uuid16(), find_ccc(), gatt_db_attribute_get_service_uuid(), le_to_uuid(), notify_chrc_create(), and register_service_changed().
int bt_uuid32_create (bt_uuid_t * btuuid, uint32_t value)
Definition at line 117 of file uuid.c.
References bt_uuid_t::type, bt_uuid_t::u32, and bt_uuid_t::value.
Referenced by bt_string_to_uuid32(), and le_to_uuid().
int bt_uuid_cmp (const bt_uuid_t * uuid1, const bt_uuid_t * uuid2)
Definition at line 135 of file uuid.c.
References bt_uuid128_cmp(), and bt_uuid_to_uuid128().
Referenced by find_by_type(), find_ccc(), find_service_with_uuid(), foreach_service_in_range(), gatt_db_attribute_get_char_data(), gatt_db_attribute_get_incl_data(), gatt_db_attribute_get_service_data(), gatt_db_insert_service(), gatt_db_read_by_group_type(), gatt_db_service_foreach(), gatt_db_service_foreach_desc(), notify_chrc_create(), and read_by_type().
static int bt_uuid_len (const bt_uuid_t * uuid) inline static
Definition at line 172 of file uuid.h.
References bt_uuid_t::type.
Referenced by uuid_to_le().
int bt_uuid_strcmp (const void * a, const void * b)
Definition at line 299 of file uuid.c.
int bt_uuid_to_le (const bt_uuid_t * uuid, void * dst)
Definition at line 304 of file uuid.c.
References bswap_128(), bt_put_le16(), bt_uuid32_to_uuid128(), bt_uuid_t::type, bt_uuid_t::u128, bt_uuid_t::u16, and bt_uuid_t::value.
Referenced by bt_gatt_read_by_type(), discover_services(), find_by_type_val_cb(), and read_by_type_cb().
int bt_uuid_to_string (const bt_uuid_t * uuid, char * str, size_t n)
Definition at line 148 of file uuid.c.
References bt_uuid_t::type, bt_uuid_t::u128, bt_uuid_t::u16, bt_uuid_t::u32, and bt_uuid_t::value.
Referenced by discover_chrcs_cb(), discover_descs_cb(), discover_incl_cb(), discover_primary_cb(), discover_secondary_cb(), log_service_event(), and print_uuid().
void bt_uuid_to_uuid128 (const bt_uuid_t * src, bt_uuid_t * dst)
Definition at line 85 of file uuid.c.
References bt_uuid16_to_uuid128(), bt_uuid32_to_uuid128(), and bt_uuid_t::type.
Referenced by bt_gatt_iter_next_service(), bt_uuid_cmp(), cmd_services(), print_uuid(), and uuid_to_le().