ble_gatt_client: src/uuid.c File Reference
uuid.c File Reference
uuid collection of functions
#include <string.h>
#include <stdlib.h>
#include <errno.h>
#include "bluetooth.h"
#include "uuid.h"
Macros
#define BASE_UUID16_OFFSET 2
#define BASE_UUID32_OFFSET 0
Functions
static void bt_uuid16_to_uuid128 (const bt_uuid_t *src, bt_uuid_t *dst)
static void bt_uuid32_to_uuid128 (const bt_uuid_t *src, bt_uuid_t *dst)
void bt_uuid_to_uuid128 (const bt_uuid_t *src, bt_uuid_t *dst)
static int bt_uuid128_cmp (const bt_uuid_t *u1, const bt_uuid_t *u2)
int bt_uuid16_create (bt_uuid_t *btuuid, uint16_t value)
int bt_uuid32_create (bt_uuid_t *btuuid, uint32_t value)
int bt_uuid128_create (bt_uuid_t *btuuid, uint128_t value)
int bt_uuid_cmp (const bt_uuid_t *uuid1, const bt_uuid_t *uuid2)
int bt_uuid_to_string (const bt_uuid_t *uuid, char *str, size_t n)
static int is_uuid128 (const char *string)
static int is_base_uuid128 (const char *string)
static int is_uuid32 (const char *string)
static int is_uuid16 (const char *string)
static int bt_string_to_uuid16 (bt_uuid_t *uuid, const char *string)
static int bt_string_to_uuid32 (bt_uuid_t *uuid, const char *string)
static int bt_string_to_uuid128 (bt_uuid_t *uuid, const char *string)
int bt_string_to_uuid (bt_uuid_t *uuid, const char *string)
int bt_uuid_strcmp (const void *a, const void *b)
int bt_uuid_to_le (const bt_uuid_t *src, void *dst)
Variables
static uint128_t bluetooth_base_uuid
Detailed Description
uuid collection of functions
Author
Gilbert Brault
Copyright
Gilbert Brault 2015 the original work comes from bluez v5.39 value add: documenting main features
Definition in file uuid.c.
Macro Definition Documentation
#define BASE_UUID16_OFFSET 2
Definition at line 50 of file uuid.c.
Referenced by bt_uuid16_to_uuid128().
#define BASE_UUID32_OFFSET 0
Definition at line 51 of file uuid.c.
Referenced by bt_uuid32_to_uuid128().
Function Documentation
int bt_string_to_uuid (bt_uuid_t * uuid, const char * string)
Definition at line 285 of file uuid.c.
References bt_string_to_uuid128(), bt_string_to_uuid16(), bt_string_to_uuid32(), is_base_uuid128(), is_uuid128(), is_uuid16(), and is_uuid32().
Referenced by cmd_services().
static int bt_string_to_uuid128 (bt_uuid_t * uuid, const char * string) static
Definition at line 254 of file uuid.c.
References bt_uuid128_create().
Referenced by bt_string_to_uuid().
static int bt_string_to_uuid16 (bt_uuid_t * uuid, const char * string) static
Definition at line 226 of file uuid.c.
References bt_uuid16_create().
Referenced by bt_string_to_uuid().
static int bt_string_to_uuid32 (bt_uuid_t * uuid, const char * string) static
Definition at line 240 of file uuid.c.
References bt_uuid32_create().
Referenced by bt_string_to_uuid().
static int bt_uuid128_cmp (const bt_uuid_t * u1, const bt_uuid_t * u2) static
Definition at line 103 of file uuid.c.
References bt_uuid_t::u128, and bt_uuid_t::value.
Referenced by bt_uuid_cmp().
int bt_uuid128_create (bt_uuid_t * btuuid, uint128_t value)
Definition at line 126 of file uuid.c.
References bt_uuid_t::type, bt_uuid_t::u128, and bt_uuid_t::value.
Referenced by bt_string_to_uuid128(), discover_chrcs_cb(), discover_descs_cb(), discover_incl_cb(), discover_primary_cb(), discover_secondary_cb(), gatt_db_attribute_get_service_uuid(), and le_to_uuid().
int bt_uuid16_create (bt_uuid_t * btuuid, uint16_t value)
Definition at line 108 of file uuid.c.
References bt_uuid_t::type, bt_uuid_t::u16, and bt_uuid_t::value.
Referenced by bt_string_to_uuid16(), find_ccc(), gatt_db_attribute_get_service_uuid(), le_to_uuid(), notify_chrc_create(), and register_service_changed().
static void bt_uuid16_to_uuid128 (const bt_uuid_t * src, bt_uuid_t * dst) static
Definition at line 53 of file uuid.c.
References BASE_UUID16_OFFSET, bluetooth_base_uuid, uint128_t::data, bt_uuid_t::type, bt_uuid_t::u128, bt_uuid_t::u16, and bt_uuid_t::value.
Referenced by bt_uuid_to_uuid128().
int bt_uuid32_create (bt_uuid_t * btuuid, uint32_t value)
Definition at line 117 of file uuid.c.
References bt_uuid_t::type, bt_uuid_t::u32, and bt_uuid_t::value.
Referenced by bt_string_to_uuid32(), and le_to_uuid().
static void bt_uuid32_to_uuid128 (const bt_uuid_t * src, bt_uuid_t * dst) static
Definition at line 69 of file uuid.c.
References BASE_UUID32_OFFSET, bluetooth_base_uuid, uint128_t::data, bt_uuid_t::type, bt_uuid_t::u128, bt_uuid_t::u32, and bt_uuid_t::value.
Referenced by bt_uuid_to_le(), and bt_uuid_to_uuid128().
int bt_uuid_cmp (const bt_uuid_t * uuid1, const bt_uuid_t * uuid2)
Definition at line 135 of file uuid.c.
References bt_uuid128_cmp(), and bt_uuid_to_uuid128().
Referenced by find_by_type(), find_ccc(), find_service_with_uuid(), foreach_service_in_range(), gatt_db_attribute_get_char_data(), gatt_db_attribute_get_incl_data(), gatt_db_attribute_get_service_data(), gatt_db_insert_service(), gatt_db_read_by_group_type(), gatt_db_service_foreach(), gatt_db_service_foreach_desc(), notify_chrc_create(), and read_by_type().
int bt_uuid_strcmp (const void * a, const void * b)
Definition at line 299 of file uuid.c.
int bt_uuid_to_le (const bt_uuid_t * src, void * dst)
Definition at line 304 of file uuid.c.
References bswap_128(), bt_put_le16(), bt_uuid32_to_uuid128(), bt_uuid_t::type, bt_uuid_t::u128, bt_uuid_t::u16, and bt_uuid_t::value.
Referenced by bt_gatt_read_by_type(), discover_services(), find_by_type_val_cb(), and read_by_type_cb().
int bt_uuid_to_string (const bt_uuid_t * uuid, char * str, size_t n)
Definition at line 148 of file uuid.c.
References bt_uuid_t::type, bt_uuid_t::u128, bt_uuid_t::u16, bt_uuid_t::u32, and bt_uuid_t::value.
Referenced by discover_chrcs_cb(), discover_descs_cb(), discover_incl_cb(), discover_primary_cb(), discover_secondary_cb(), log_service_event(), and print_uuid().
void bt_uuid_to_uuid128 (const bt_uuid_t * src, bt_uuid_t * dst)
Definition at line 85 of file uuid.c.
References bt_uuid16_to_uuid128(), bt_uuid32_to_uuid128(), and bt_uuid_t::type.
Referenced by bt_gatt_iter_next_service(), bt_uuid_cmp(), cmd_services(), print_uuid(), and uuid_to_le().
static int is_base_uuid128 (const char * string) inline static
Definition at line 203 of file uuid.c.
References is_uuid128().
Referenced by bt_string_to_uuid().
static int is_uuid128 (const char * string) inline static
Definition at line 194 of file uuid.c.
Referenced by bt_string_to_uuid(), and is_base_uuid128().
static int is_uuid16 (const char * string) inline static
Definition at line 221 of file uuid.c.
Referenced by bt_string_to_uuid().
static int is_uuid32 (const char * string) inline static
Definition at line 216 of file uuid.c.
Referenced by bt_string_to_uuid().
Variable Documentation
uint128_t bluetooth_base_uuid static
Initial value:
= {
    .data = {   0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x10, 0x00,
            0x80, 0x00, 0x00, 0x80, 0x5F, 0x9B, 0x34, 0xFB }
}
Definition at line 45 of file uuid.c.
Referenced by bt_uuid16_to_uuid128(), and bt_uuid32_to_uuid128().